//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_ndo_dbproperty
    {
        public int programid { get; set; }
        public byte[] chartable { get; set; }
        public int maxrecsize { get; set; }
        public int maxloginattempts { get; set; }
        public int passwordexpindays { get; set; }
        public string supergroupid { get; set; }
        public byte unifiedloginallowed { get; set; }
        public int contype { get; set; }
        public string shadowpwd { get; set; }
        public int databasemagic { get; set; }
        public int databaseversionno { get; set; }
        public int clientdatabaseversionno { get; set; }
        public int maintainviews { get; set; }
        public int diagnostics { get; set; }
        public string identifiers { get; set; }
        public int maintainrelationships { get; set; }
        public int convertidentifiers { get; set; }
        public string invalididentifierchars { get; set; }
        public byte[] license { get; set; }
        public int checkcodepage { get; set; }
        public int quickfind { get; set; }
        public int maintaindefaults { get; set; }
        public int locktimeout { get; set; }
        public int locktimeoutperiod { get; set; }
        public int hardrowlock { get; set; }
        public int bufferedrows { get; set; }
        public int securityoption { get; set; }
        public int enabledforserver { get; set; }
        public int uidoffset { get; set; }
    }
}
