//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Debugger_Breakpoint
    {
        public byte[] timestamp { get; set; }
        public int Breakpoint_ID { get; set; }
        public int Object_Type { get; set; }
        public int Object_ID { get; set; }
        public int Line_No_ { get; set; }
        public int Column_No_ { get; set; }
        public int End_Line_No_ { get; set; }
        public int End_Column_No_ { get; set; }
        public string Function_Name { get; set; }
        public byte Enabled { get; set; }
        public string Condition { get; set; }
        public long Session_Breakpoint_ID { get; set; }
        public int Relative_Line_No_ { get; set; }
        public int Relative_End_Line_No_ { get; set; }
        public int Function_ID { get; set; }
    }
}
