//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        public byte[] timestamp { get; set; }
        public string MAC_Address { get; set; }
        public string Name { get; set; }
        public int Device_Type { get; set; }
        public byte Enabled { get; set; }
    }
}
