//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLINTEC_Segment_History
    {
        public byte[] timestamp { get; set; }
        public string Segment_No_ { get; set; }
        public int Segment_Action_No_ { get; set; }
        public int Segment_Line_No_ { get; set; }
        public string Contact_No_ { get; set; }
        public int Action_Taken { get; set; }
    }
}
