//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLINTEC_Chemical_Master
    {
        public byte[] timestamp { get; set; }
        public string Item_No_ { get; set; }
        public string Flintec_Part_No_ { get; set; }
        public string Description { get; set; }
        public byte Roh_Compatability { get; set; }
        public string From_DOS { get; set; }
        public string From_DOP { get; set; }
        public string From_DOM { get; set; }
        public int Existing_Storage_Condition { get; set; }
        public string Recomended_Storage_Condition { get; set; }
        public byte MSDS_Availability { get; set; }
        public string User { get; set; }
        public decimal Health_Hazard { get; set; }
        public decimal Flamability { get; set; }
        public decimal Reactivity { get; set; }
        public decimal DOT_Hazard_Class { get; set; }
        public string Comment { get; set; }
        public byte Hazardous { get; set; }
    }
}
