//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLINTEC_Prod__Order_Rtng_Qlty_Meas_
    {
        public byte[] timestamp { get; set; }
        public int Status { get; set; }
        public string Prod__Order_No_ { get; set; }
        public int Routing_Reference_No_ { get; set; }
        public string Routing_No_ { get; set; }
        public string Operation_No_ { get; set; }
        public int Line_No_ { get; set; }
        public string Qlty_Measure_Code { get; set; }
        public string Description { get; set; }
        public decimal Min__Value { get; set; }
        public decimal Max__Value { get; set; }
        public decimal Mean_Tolerance { get; set; }
    }
}
