//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLINTEC_Production_BOM_Line
    {
        public byte[] timestamp { get; set; }
        public string Production_BOM_No_ { get; set; }
        public string Version_Code { get; set; }
        public int Line_No_ { get; set; }
        public int Type { get; set; }
        public string No_ { get; set; }
        public string Description { get; set; }
        public string Unit_of_Measure_Code { get; set; }
        public decimal Quantity { get; set; }
        public string Position { get; set; }
        public string Position_2 { get; set; }
        public string Position_3 { get; set; }
        public string Lead_Time_Offset { get; set; }
        public string Routing_Link_Code { get; set; }
        public decimal Scrap__ { get; set; }
        public string Variant_Code { get; set; }
        public System.DateTime Starting_Date { get; set; }
        public System.DateTime Ending_Date { get; set; }
        public decimal Length { get; set; }
        public decimal Width { get; set; }
        public decimal Weight { get; set; }
        public decimal Depth { get; set; }
        public int Calculation_Formula { get; set; }
        public decimal Quantity_per { get; set; }
        public string Addnl__Description { get; set; }
        public byte Mark_Line_For_Exchange { get; set; }
        public byte Mark_For_Deletion { get; set; }
    }
}
