//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLINTEC_Item_Category
    {
        public byte[] timestamp { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public string Def__Gen__Prod__Posting_Group { get; set; }
        public string Def__Inventory_Posting_Group { get; set; }
        public string Def__Tax_Group_Code { get; set; }
        public int Def__Costing_Method { get; set; }
        public string Def__VAT_Prod__Posting_Group { get; set; }
    }
}
