//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLINTEC_Item_Availability_by_Date
    {
        public byte[] timestamp { get; set; }
        public string Item_No_ { get; set; }
        public string Variant_Code { get; set; }
        public string Location_Code { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Available_Qty { get; set; }
        public decimal Updated_Available_Qty { get; set; }
    }
}
