//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLINTEC_Analysis_Line
    {
        public byte[] timestamp { get; set; }
        public int Analysis_Area { get; set; }
        public string Analysis_Line_Template_Name { get; set; }
        public int Line_No_ { get; set; }
        public string Row_Ref__No_ { get; set; }
        public string Description { get; set; }
        public int Type { get; set; }
        public string Range { get; set; }
        public byte New_Page { get; set; }
        public int Show { get; set; }
        public byte Bold { get; set; }
        public byte Italic { get; set; }
        public byte Underline { get; set; }
        public byte Show_Opposite_Sign { get; set; }
        public string Dimension_1_Totaling { get; set; }
        public string Dimension_2_Totaling { get; set; }
        public string Dimension_3_Totaling { get; set; }
        public string Group_Dimension_Code { get; set; }
        public int Indentation { get; set; }
    }
}
