//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLINTEC_SMTP_Mail_Setup
    {
        public byte[] timestamp { get; set; }
        public string Primary_Key { get; set; }
        public string SMTP_Server { get; set; }
        public int Authentication { get; set; }
        public string User_ID { get; set; }
        public string Password { get; set; }
        public int SMTP_Server_Port { get; set; }
        public byte Secure_Connection { get; set; }
    }
}
