//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLINTEC_Opportunity
    {
        public byte[] timestamp { get; set; }
        public string No_ { get; set; }
        public string Description { get; set; }
        public string Salesperson_Code { get; set; }
        public string Campaign_No_ { get; set; }
        public string Contact_No_ { get; set; }
        public string Contact_Company_No_ { get; set; }
        public string Sales_Cycle_Code { get; set; }
        public string Sales_Document_No_ { get; set; }
        public System.DateTime Creation_Date { get; set; }
        public int Status { get; set; }
        public int Priority { get; set; }
        public byte Closed { get; set; }
        public System.DateTime Date_Closed { get; set; }
        public string No__Series { get; set; }
        public string Segment_No_ { get; set; }
        public int Sales_Document_Type { get; set; }
        public int Wizard_Step { get; set; }
        public byte Activate_First_Stage { get; set; }
        public string Segment_Description { get; set; }
        public decimal Wizard_Estimated_Value__LCY_ { get; set; }
        public decimal Wizard_Chances_of_Success__ { get; set; }
        public System.DateTime Wizard_Estimated_Closing_Date { get; set; }
        public string Wizard_Contact_Name { get; set; }
        public string Wizard_Campaign_Description { get; set; }
    }
}
