//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLINTEC_Product_Group_Code_Multiplier
    {
        public byte[] timestamp { get; set; }
        public string Product_Group_Code { get; set; }
        public decimal Multiplier { get; set; }
    }
}
