//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLINTEC_Standard_Customer_Sales_Code
    {
        public byte[] timestamp { get; set; }
        public string Customer_No_ { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public System.DateTime Valid_From_Date { get; set; }
        public System.DateTime Valid_To_date { get; set; }
        public string Payment_Method_Code { get; set; }
        public string Payment_Terms_Code { get; set; }
        public string Direct_Debit_Mandate_ID { get; set; }
        public byte Blocked { get; set; }
    }
}
