//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLINTEC_VAT_Report_Line_Relation
    {
        public byte[] timestamp { get; set; }
        public string VAT_Report_No_ { get; set; }
        public int VAT_Report_Line_No_ { get; set; }
        public int Line_No_ { get; set; }
        public int Table_No_ { get; set; }
        public int Entry_No_ { get; set; }
    }
}
