//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLINTEC_Outlook_Synch__User_Setup
    {
        public byte[] timestamp { get; set; }
        public string User_ID { get; set; }
        public string Synch__Entity_Code { get; set; }
        public string Condition { get; set; }
        public int Synch__Direction { get; set; }
        public System.DateTime Last_Synch__Time { get; set; }
        public System.Guid Record_GUID { get; set; }
    }
}
