//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLINTEC_Excel_Buffer
    {
        public byte[] timestamp { get; set; }
        public int Row_No_ { get; set; }
        public int Column_No_ { get; set; }
        public string xlRowID { get; set; }
        public string xlColID { get; set; }
        public string Cell_Value_as_Text { get; set; }
        public string Comment { get; set; }
        public string Formula { get; set; }
        public byte Bold { get; set; }
        public byte Italic { get; set; }
        public byte Underline { get; set; }
        public string NumberFormat { get; set; }
        public string Formula2 { get; set; }
        public string Formula3 { get; set; }
        public string Formula4 { get; set; }
        public int Cell_Type { get; set; }
    }
}
