//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLINTEC_Incoming_Documents_Setup
    {
        public byte[] timestamp { get; set; }
        public string Primary_Key { get; set; }
        public string General_Journal_Template_Name { get; set; }
        public string General_Journal_Batch_Name { get; set; }
        public byte Require_Approval_To_Create { get; set; }
    }
}
