//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLINTEC_Posted_Whse__Shipment_Line
    {
        public byte[] timestamp { get; set; }
        public string No_ { get; set; }
        public int Line_No_ { get; set; }
        public int Source_Type { get; set; }
        public int Source_Subtype { get; set; }
        public string Source_No_ { get; set; }
        public int Source_Line_No_ { get; set; }
        public int Source_Document { get; set; }
        public string Location_Code { get; set; }
        public string Shelf_No_ { get; set; }
        public string Bin_Code { get; set; }
        public string Zone_Code { get; set; }
        public string Item_No_ { get; set; }
        public decimal Quantity { get; set; }
        public decimal Qty___Base_ { get; set; }
        public string Unit_of_Measure_Code { get; set; }
        public decimal Qty__per_Unit_of_Measure { get; set; }
        public string Variant_Code { get; set; }
        public string Description { get; set; }
        public string Description_2 { get; set; }
        public System.DateTime Due_Date { get; set; }
        public int Destination_Type { get; set; }
        public string Destination_No_ { get; set; }
        public int Shipping_Advice { get; set; }
        public System.DateTime Shipment_Date { get; set; }
        public int Posted_Source_Document { get; set; }
        public string Posted_Source_No_ { get; set; }
        public System.DateTime Posting_Date { get; set; }
        public string Whse__Shipment_No_ { get; set; }
        public int Whse_Shipment_Line_No_ { get; set; }
    }
}
