//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLINTEC_VAT_Report_Setup
    {
        public byte[] timestamp { get; set; }
        public string Primary_key { get; set; }
        public string No__Series { get; set; }
        public byte Modify_Submitted_Reports { get; set; }
    }
}
