//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLINTEC_Job_Posting_Buffer
    {
        public byte[] timestamp { get; set; }
        public string Job_No_ { get; set; }
        public int Entry_Type { get; set; }
        public int Posting_Group_Type { get; set; }
        public string No_ { get; set; }
        public string Variant_Code { get; set; }
        public string Posting_Group { get; set; }
        public string Gen__Bus__Posting_Group { get; set; }
        public string Gen__Prod__Posting_Group { get; set; }
        public string Unit_of_Measure_Code { get; set; }
        public string Work_Type_Code { get; set; }
        public int Dimension_Entry_No_ { get; set; }
        public string Global_Dimension_1_Code { get; set; }
        public string Global_Dimension_2_Code { get; set; }
        public decimal Amount { get; set; }
        public decimal Quantity { get; set; }
        public decimal Total_Cost { get; set; }
        public decimal Total_Price { get; set; }
        public string Applies_to_ID { get; set; }
        public decimal Additional_Currency_Amount { get; set; }
        public int Dimension_Set_ID { get; set; }
    }
}
