//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLINTEC_IC_Partner
    {
        public byte[] timestamp { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Currency_Code { get; set; }
        public int Inbox_Type { get; set; }
        public string Inbox_Details { get; set; }
        public string Receivables_Account { get; set; }
        public string Payables_Account { get; set; }
        public byte Blocked { get; set; }
        public string Customer_No_ { get; set; }
        public string Vendor_No_ { get; set; }
        public int Outbound_Sales_Item_No__Type { get; set; }
        public int Outbound_Purch__Item_No__Type { get; set; }
        public byte Cost_Distribution_in_LCY { get; set; }
    }
}
