//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLINTEC_Direct_Debit_Collection
    {
        public byte[] timestamp { get; set; }
        public int No_ { get; set; }
        public string Identifier { get; set; }
        public System.DateTime Created_Date_Time { get; set; }
        public string Created_by_User { get; set; }
        public int Status { get; set; }
        public string To_Bank_Account_No_ { get; set; }
        public string Message_ID { get; set; }
        public int Partner_Type { get; set; }
    }
}
