//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLINTEC_Cost_Entry
    {
        public byte[] timestamp { get; set; }
        public int Entry_No_ { get; set; }
        public string Cost_Type_No_ { get; set; }
        public System.DateTime Posting_Date { get; set; }
        public string Document_No_ { get; set; }
        public string Description { get; set; }
        public decimal Amount { get; set; }
        public decimal Debit_Amount { get; set; }
        public decimal Credit_Amount { get; set; }
        public string Cost_Center_Code { get; set; }
        public string Cost_Object_Code { get; set; }
        public string Reason_Code { get; set; }
        public string G_L_Account { get; set; }
        public int G_L_Entry_No_ { get; set; }
        public string Source_Code { get; set; }
        public byte System_Created_Entry { get; set; }
        public byte Allocated { get; set; }
        public int Allocated_with_Journal_No_ { get; set; }
        public string User_ID { get; set; }
        public string Batch_Name { get; set; }
        public string Allocation_Description { get; set; }
        public string Allocation_ID { get; set; }
        public decimal Additional_Currency_Amount { get; set; }
        public decimal Add__Currency_Debit_Amount { get; set; }
        public decimal Add__Currency_Credit_Amount { get; set; }
    }
}
