//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLINTEC_Vendor_Amount
    {
        public byte[] timestamp { get; set; }
        public decimal Amount__LCY_ { get; set; }
        public decimal Amount_2__LCY_ { get; set; }
        public string Vendor_No_ { get; set; }
    }
}
