//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLINTEC_Service_Item_Group
    {
        public byte[] timestamp { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public byte Create_Service_Item { get; set; }
        public decimal Default_Contract_Discount__ { get; set; }
        public string Default_Serv__Price_Group_Code { get; set; }
        public decimal Default_Response_Time__Hours_ { get; set; }
    }
}
