//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLINTEC_Average_Cost_Calc__Overview
    {
        public byte[] timestamp { get; set; }
        public int Entry_No_ { get; set; }
        public int Type { get; set; }
        public System.DateTime Valuation_Date { get; set; }
        public string Item_No_ { get; set; }
        public string Location_Code { get; set; }
        public string Variant_Code { get; set; }
        public byte Cost_is_Adjusted { get; set; }
        public int Attached_to_Entry_No_ { get; set; }
        public System.DateTime Attached_to_Valuation_Date { get; set; }
        public int Level { get; set; }
        public int Item_Ledger_Entry_No_ { get; set; }
        public System.DateTime Posting_Date { get; set; }
        public int Entry_Type { get; set; }
        public int Document_Type { get; set; }
        public string Document_No_ { get; set; }
        public int Document_Line_No_ { get; set; }
        public string Description { get; set; }
        public decimal Quantity { get; set; }
        public int Applied_Quantity { get; set; }
        public decimal Cost_Amount__Expected_ { get; set; }
        public decimal Cost_Amount__Actual_ { get; set; }
    }
}
