//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLINTEC_Job_Difference_Buffer
    {
        public byte[] timestamp { get; set; }
        public string Job_No_ { get; set; }
        public string Job_Task_No_ { get; set; }
        public int Type { get; set; }
        public int Entry_type { get; set; }
        public string No_ { get; set; }
        public string Location_Code { get; set; }
        public string Variant_Code { get; set; }
        public string Unit_of_Measure_code { get; set; }
        public string Work_Type_Code { get; set; }
        public decimal Quantity { get; set; }
        public decimal Total_Cost { get; set; }
        public decimal Line_Amount { get; set; }
    }
}
