//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLINTEC_Cash_Flow_Account
    {
        public byte[] timestamp { get; set; }
        public string No_ { get; set; }
        public string Name { get; set; }
        public string Search_Name { get; set; }
        public int Account_Type { get; set; }
        public byte Blocked { get; set; }
        public byte New_Page { get; set; }
        public int No__of_Blank_Lines { get; set; }
        public int Indentation { get; set; }
        public System.DateTime Last_Date_Modified { get; set; }
        public string Totaling { get; set; }
        public int Source_Type { get; set; }
        public int G_L_Integration { get; set; }
        public string G_L_Account_Filter { get; set; }
    }
}
