//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLINTEC_Currency_for_Reminder_Level
    {
        public byte[] timestamp { get; set; }
        public string Reminder_Terms_Code { get; set; }
        public int No_ { get; set; }
        public string Currency_Code { get; set; }
        public decimal Additional_Fee { get; set; }
    }
}
