//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLINTEC_Interaction_Template_Setup
    {
        public byte[] timestamp { get; set; }
        public string Primary_Key { get; set; }
        public string Sales_Invoices { get; set; }
        public string Sales_Cr__Memo { get; set; }
        public string Sales_Ord__Cnfrmn_ { get; set; }
        public string Sales_Quotes { get; set; }
        public string Purch_Invoices { get; set; }
        public string Purch_Cr_Memos { get; set; }
        public string Purch__Orders { get; set; }
        public string Purch__Quotes { get; set; }
        public string E_Mails { get; set; }
        public string Cover_Sheets { get; set; }
        public string Outg__Calls { get; set; }
        public string Sales_Blnkt__Ord { get; set; }
        public string Serv_Ord_Post { get; set; }
        public string Sales_Shpt__Note { get; set; }
        public string Sales_Statmnt { get; set; }
        public string Sales_Rmdr_ { get; set; }
        public string Serv_Ord_Create { get; set; }
        public string Purch_Blnkt_Ord { get; set; }
        public string Purch__Rcpt_ { get; set; }
        public string Sales_Return_Order { get; set; }
        public string Sales_Return_Receipt { get; set; }
        public string Sales_Finance_Charge_Memo { get; set; }
        public string Purch__Return_Shipment { get; set; }
        public string Purch__Return_Ord__Cnfrmn_ { get; set; }
        public string Service_Contract { get; set; }
        public string Service_Contract_Quote { get; set; }
        public string Service_Quote { get; set; }
        public string Meeting_Invitation { get; set; }
    }
}
