//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLINTEC_Finance_Charge_Text
    {
        public byte[] timestamp { get; set; }
        public string Fin__Charge_Terms_Code { get; set; }
        public int Position { get; set; }
        public int Line_No_ { get; set; }
        public string Text { get; set; }
    }
}
