//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLINTEC_Warehouse_Request
    {
        public byte[] timestamp { get; set; }
        public int Type { get; set; }
        public string Location_Code { get; set; }
        public int Source_Type { get; set; }
        public int Source_Subtype { get; set; }
        public string Source_No_ { get; set; }
        public int Source_Document { get; set; }
        public int Document_Status { get; set; }
        public string Shipment_Method_Code { get; set; }
        public string Shipping_Agent_Code { get; set; }
        public int Shipping_Advice { get; set; }
        public int Destination_Type { get; set; }
        public string Destination_No_ { get; set; }
        public string External_Document_No_ { get; set; }
        public System.DateTime Expected_Receipt_Date { get; set; }
        public System.DateTime Shipment_Date { get; set; }
        public byte Completely_Handled { get; set; }
    }
}
