//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLINTEC_Mini_Item_Template
    {
        public byte[] timestamp { get; set; }
        public int Key { get; set; }
        public string Code { get; set; }
        public string Template_Name { get; set; }
        public string Base_Unit_of_Measure { get; set; }
        public int Type { get; set; }
        public string Inventory_Posting_Group { get; set; }
        public string Item_Disc__Group { get; set; }
        public byte Allow_Invoice_Disc_ { get; set; }
        public int Price_Profit_Calculation { get; set; }
        public decimal Profit__ { get; set; }
        public int Costing_Method { get; set; }
        public decimal Indirect_Cost__ { get; set; }
        public byte Price_Includes_VAT { get; set; }
        public string Gen__Prod__Posting_Group { get; set; }
        public byte Automatic_Ext__Texts { get; set; }
        public string VAT_Prod__Posting_Group { get; set; }
    }
}
