//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLINTEC_Time_Sheet_Chart_Setup
    {
        public byte[] timestamp { get; set; }
        public string User_ID { get; set; }
        public System.DateTime Starting_Date { get; set; }
        public int Show_by { get; set; }
        public int Measure_Type { get; set; }
    }
}
