//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLINTEC_Base_Calendar_Change
    {
        public byte[] timestamp { get; set; }
        public string Base_Calendar_Code { get; set; }
        public int Recurring_System { get; set; }
        public System.DateTime Date { get; set; }
        public int Day { get; set; }
        public string Description { get; set; }
        public byte Nonworking { get; set; }
    }
}
