//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLINTEC_Product_Group
    {
        public byte[] timestamp { get; set; }
        public string Item_Category_Code { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public string Warehouse_Class_Code { get; set; }
    }
}
