//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLINTEC_Extended_Text_Line
    {
        public byte[] timestamp { get; set; }
        public int Table_Name { get; set; }
        public string No_ { get; set; }
        public string Language_Code { get; set; }
        public int Text_No_ { get; set; }
        public int Line_No_ { get; set; }
        public string Text { get; set; }
    }
}
