//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLINTEC_Prod__Order_Capacity_Need
    {
        public byte[] timestamp { get; set; }
        public int Status { get; set; }
        public string Prod__Order_No_ { get; set; }
        public byte Requested_Only { get; set; }
        public string Routing_No_ { get; set; }
        public int Routing_Reference_No_ { get; set; }
        public string Operation_No_ { get; set; }
        public int Line_No_ { get; set; }
        public int Type { get; set; }
        public string No_ { get; set; }
        public string Work_Center_No_ { get; set; }
        public string Work_Center_Group_Code { get; set; }
        public System.DateTime Date { get; set; }
        public System.DateTime Starting_Time { get; set; }
        public System.DateTime Ending_Time { get; set; }
        public decimal Allocated_Time { get; set; }
        public int Send_Ahead_Type { get; set; }
        public int Time_Type { get; set; }
        public decimal Needed_Time { get; set; }
        public decimal Needed_Time__ms_ { get; set; }
        public decimal Lot_Size { get; set; }
        public decimal Concurrent_Capacities { get; set; }
        public decimal Efficiency { get; set; }
        public System.DateTime Starting_Date_Time { get; set; }
        public System.DateTime Ending_Date_Time { get; set; }
        public string Worksheet_Template_Name { get; set; }
        public string Worksheet_Batch_Name { get; set; }
        public int Worksheet_Line_No_ { get; set; }
        public byte Active { get; set; }
    }
}
