//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLINTEC_FA_Reclass__Journal_Line
    {
        public byte[] timestamp { get; set; }
        public string Journal_Template_Name { get; set; }
        public string Journal_Batch_Name { get; set; }
        public int Line_No_ { get; set; }
        public string FA_No_ { get; set; }
        public string New_FA_No_ { get; set; }
        public System.DateTime FA_Posting_Date { get; set; }
        public System.DateTime Posting_Date { get; set; }
        public string Depreciation_Book_Code { get; set; }
        public decimal Reclassify_Acq__Cost_Amount { get; set; }
        public decimal Reclassify_Acq__Cost__ { get; set; }
        public byte Reclassify_Acquisition_Cost { get; set; }
        public byte Reclassify_Depreciation { get; set; }
        public byte Reclassify_Write_Down { get; set; }
        public byte Reclassify_Appreciation { get; set; }
        public byte Reclassify_Custom_1 { get; set; }
        public byte Reclassify_Custom_2 { get; set; }
        public byte Reclassify_Salvage_Value { get; set; }
        public byte Insert_Bal__Account { get; set; }
        public string Description { get; set; }
        public string Document_No_ { get; set; }
        public byte Calc__DB1_Depr__Amount { get; set; }
    }
}
