//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLINTEC_Online_Map_Parameter_Setup
    {
        public byte[] timestamp { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Map_URL { get; set; }
        public string Directions_URL { get; set; }
        public string Comment { get; set; }
        public byte URL_Encode_Non_ASCII_Chars { get; set; }
        public string Miles_Kilometers_Option_List { get; set; }
        public string Quickest_Shortest_Option_List { get; set; }
    }
}
