//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLINTEC_Contact_Web_Source
    {
        public byte[] timestamp { get; set; }
        public string Contact_No_ { get; set; }
        public string Web_Source_Code { get; set; }
        public string Search_Word { get; set; }
    }
}
