//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLINTEC_Entry_No__Amount_Buffer
    {
        public byte[] timestamp { get; set; }
        public string Business_Unit_Code { get; set; }
        public int Entry_No_ { get; set; }
        public decimal Amount { get; set; }
        public decimal Amount2 { get; set; }
        public System.DateTime Start_Date { get; set; }
        public System.DateTime End_Date { get; set; }
    }
}
