//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLINTEC_Service_Contract_Line
    {
        public byte[] timestamp { get; set; }
        public int Contract_Type { get; set; }
        public string Contract_No_ { get; set; }
        public int Line_No_ { get; set; }
        public int Contract_Status { get; set; }
        public string Service_Item_No_ { get; set; }
        public string Description { get; set; }
        public string Serial_No_ { get; set; }
        public string Service_Item_Group_Code { get; set; }
        public string Customer_No_ { get; set; }
        public string Ship_to_Code { get; set; }
        public string Item_No_ { get; set; }
        public string Unit_of_Measure_Code { get; set; }
        public decimal Response_Time__Hours_ { get; set; }
        public System.DateTime Last_Planned_Service_Date { get; set; }
        public System.DateTime Next_Planned_Service_Date { get; set; }
        public System.DateTime Last_Service_Date { get; set; }
        public System.DateTime Last_Preventive_Maint__Date { get; set; }
        public System.DateTime Invoiced_to_Date { get; set; }
        public System.DateTime Credit_Memo_Date { get; set; }
        public System.DateTime Contract_Expiration_Date { get; set; }
        public string Service_Period { get; set; }
        public decimal Line_Value { get; set; }
        public decimal Line_Discount__ { get; set; }
        public decimal Line_Amount { get; set; }
        public string Variant_Code { get; set; }
        public System.DateTime Starting_Date { get; set; }
        public byte New_Line { get; set; }
        public byte Credited { get; set; }
        public decimal Line_Cost { get; set; }
        public decimal Line_Discount_Amount { get; set; }
        public decimal Profit { get; set; }
    }
}
