//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLINTEC_Campaign_Target_Group
    {
        public byte[] timestamp { get; set; }
        public int Type { get; set; }
        public string No_ { get; set; }
        public string Campaign_No_ { get; set; }
    }
}
