//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLINTEC_Dimension_ID_Buffer
    {
        public byte[] timestamp { get; set; }
        public int Parent_ID { get; set; }
        public string Dimension_Code { get; set; }
        public string Dimension_Value { get; set; }
        public int ID { get; set; }
    }
}
