//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLINTEC_Resource_Skill
    {
        public byte[] timestamp { get; set; }
        public int Type { get; set; }
        public string No_ { get; set; }
        public string Skill_Code { get; set; }
        public int Assigned_From { get; set; }
        public int Source_Type { get; set; }
        public string Source_Code { get; set; }
    }
}
