//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLINTEC_Service_Invoice_Header
    {
        public byte[] timestamp { get; set; }
        public string No_ { get; set; }
        public string Customer_No_ { get; set; }
        public string Bill_to_Customer_No_ { get; set; }
        public string Bill_to_Name { get; set; }
        public string Bill_to_Name_2 { get; set; }
        public string Bill_to_Address { get; set; }
        public string Bill_to_Address_2 { get; set; }
        public string Bill_to_City { get; set; }
        public string Bill_to_Contact { get; set; }
        public string Your_Reference { get; set; }
        public string Ship_to_Code { get; set; }
        public string Ship_to_Name { get; set; }
        public string Ship_to_Name_2 { get; set; }
        public string Ship_to_Address { get; set; }
        public string Ship_to_Address_2 { get; set; }
        public string Ship_to_City { get; set; }
        public string Ship_to_Contact { get; set; }
        public System.DateTime Order_Date { get; set; }
        public System.DateTime Posting_Date { get; set; }
        public string Posting_Description { get; set; }
        public string Payment_Terms_Code { get; set; }
        public System.DateTime Due_Date { get; set; }
        public decimal Payment_Discount__ { get; set; }
        public System.DateTime Pmt__Discount_Date { get; set; }
        public string Location_Code { get; set; }
        public string Shortcut_Dimension_1_Code { get; set; }
        public string Shortcut_Dimension_2_Code { get; set; }
        public string Customer_Posting_Group { get; set; }
        public string Currency_Code { get; set; }
        public decimal Currency_Factor { get; set; }
        public string Customer_Price_Group { get; set; }
        public byte Prices_Including_VAT { get; set; }
        public string Invoice_Disc__Code { get; set; }
        public string Customer_Disc__Group { get; set; }
        public string Language_Code { get; set; }
        public string Salesperson_Code { get; set; }
        public string Order_No_ { get; set; }
        public int No__Printed { get; set; }
        public int Applies_to_Doc__Type { get; set; }
        public string Applies_to_Doc__No_ { get; set; }
        public string Bal__Account_No_ { get; set; }
        public string Shipping_No_ { get; set; }
        public string Posting_No_ { get; set; }
        public string Last_Shipping_No_ { get; set; }
        public string Last_Posting_No_ { get; set; }
        public string VAT_Registration_No_ { get; set; }
        public string Reason_Code { get; set; }
        public string Gen__Bus__Posting_Group { get; set; }
        public byte EU_3_Party_Trade { get; set; }
        public string Transaction_Type { get; set; }
        public string Transport_Method { get; set; }
        public string VAT_Country_Region_Code { get; set; }
        public string Name { get; set; }
        public string Name_2 { get; set; }
        public string Address { get; set; }
        public string Address_2 { get; set; }
        public string City { get; set; }
        public string Contact_Name { get; set; }
        public string Bill_to_Post_Code { get; set; }
        public string Bill_to_County { get; set; }
        public string Bill_to_Country_Region_Code { get; set; }
        public string Post_Code { get; set; }
        public string County { get; set; }
        public string Country_Region_Code { get; set; }
        public string Ship_to_Post_Code { get; set; }
        public string Ship_to_County { get; set; }
        public string Ship_to_Country_Region_Code { get; set; }
        public int Bal__Account_Type { get; set; }
        public string Exit_Point { get; set; }
        public byte Correction { get; set; }
        public System.DateTime Document_Date { get; set; }
        public string Area { get; set; }
        public string Transaction_Specification { get; set; }
        public string Payment_Method_Code { get; set; }
        public string Pre_Assigned_No__Series { get; set; }
        public string No__Series { get; set; }
        public string Shipping_No__Series { get; set; }
        public string Order_No__Series { get; set; }
        public string Pre_Assigned_No_ { get; set; }
        public string User_ID { get; set; }
        public string Source_Code { get; set; }
        public string Tax_Area_Code { get; set; }
        public byte Tax_Liable { get; set; }
        public string VAT_Bus__Posting_Group { get; set; }
        public decimal VAT_Base_Discount__ { get; set; }
        public int Dimension_Set_ID { get; set; }
        public string Contact_No_ { get; set; }
        public string Bill_to_Contact_No_ { get; set; }
        public string Responsibility_Center { get; set; }
        public string Description { get; set; }
        public string Service_Order_Type { get; set; }
        public byte Link_Service_to_Service_Item { get; set; }
        public int Priority { get; set; }
        public string Phone_No_ { get; set; }
        public string E_Mail { get; set; }
        public string Phone_No__2 { get; set; }
        public string Fax_No_ { get; set; }
        public System.DateTime Order_Time { get; set; }
        public decimal Default_Response_Time__Hours_ { get; set; }
        public decimal Actual_Response_Time__Hours_ { get; set; }
        public decimal Service_Time__Hours_ { get; set; }
        public System.DateTime Response_Date { get; set; }
        public System.DateTime Response_Time { get; set; }
        public System.DateTime Starting_Date { get; set; }
        public System.DateTime Starting_Time { get; set; }
        public System.DateTime Finishing_Date { get; set; }
        public System.DateTime Finishing_Time { get; set; }
        public int Notify_Customer { get; set; }
        public decimal Max__Labor_Unit_Price { get; set; }
        public int Warning_Status { get; set; }
        public string Contract_No_ { get; set; }
        public string Ship_to_Fax_No_ { get; set; }
        public string Ship_to_E_Mail { get; set; }
        public string Ship_to_Phone { get; set; }
        public string Ship_to_Phone_2 { get; set; }
        public string Service_Zone_Code { get; set; }
        public System.DateTime Expected_Finishing_Date { get; set; }
        public byte Allow_Line_Disc_ { get; set; }
    }
}
