//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLINTEC_Depreciation_Table_Line
    {
        public byte[] timestamp { get; set; }
        public string Depreciation_Table_Code { get; set; }
        public int Period_No_ { get; set; }
        public decimal Period_Depreciation__ { get; set; }
        public decimal No__of_Units_in_Period { get; set; }
    }
}
