//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLINTEC_Vendor_Bank_Account
    {
        public byte[] timestamp { get; set; }
        public string Vendor_No_ { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Name_2 { get; set; }
        public string Address { get; set; }
        public string Address_2 { get; set; }
        public string City { get; set; }
        public string Post_Code { get; set; }
        public string Contact { get; set; }
        public string Phone_No_ { get; set; }
        public string Telex_No_ { get; set; }
        public string Bank_Branch_No_ { get; set; }
        public string Bank_Account_No_ { get; set; }
        public string Transit_No_ { get; set; }
        public string Currency_Code { get; set; }
        public string Country_Region_Code { get; set; }
        public string County { get; set; }
        public string Fax_No_ { get; set; }
        public string Telex_Answer_Back { get; set; }
        public string Language_Code { get; set; }
        public string E_Mail { get; set; }
        public string Home_Page { get; set; }
        public string IBAN { get; set; }
        public string SWIFT_Code { get; set; }
    }
}
