//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLINTEC_Inventory_Buffer
    {
        public byte[] timestamp { get; set; }
        public string Item_No_ { get; set; }
        public string Variant_Code { get; set; }
        public int Dimension_Entry_No_ { get; set; }
        public string Location_Code { get; set; }
        public string Bin_Code { get; set; }
        public string Lot_No_ { get; set; }
        public string Serial_No_ { get; set; }
        public decimal Quantity { get; set; }
    }
}
