//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLINTEC_Capacity_Constrained_Resource
    {
        public byte[] timestamp { get; set; }
        public int Capacity_Type { get; set; }
        public string Capacity_No_ { get; set; }
        public string Name { get; set; }
        public decimal Critical_Load__ { get; set; }
        public decimal Dampener____of_Total_Capacity_ { get; set; }
        public string Work_Center_No_ { get; set; }
    }
}
