//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLINTEC_Dimension_Set_Tree_Node
    {
        public byte[] timestamp { get; set; }
        public int Parent_Dimension_Set_ID { get; set; }
        public int Dimension_Value_ID { get; set; }
        public int Dimension_Set_ID { get; set; }
        public byte In_Use { get; set; }
    }
}
