//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLINTEC_VAT_Statement_Line
    {
        public byte[] timestamp { get; set; }
        public string Statement_Template_Name { get; set; }
        public string Statement_Name { get; set; }
        public int Line_No_ { get; set; }
        public string Row_No_ { get; set; }
        public string Description { get; set; }
        public int Type { get; set; }
        public string Account_Totaling { get; set; }
        public int Gen__Posting_Type { get; set; }
        public string VAT_Bus__Posting_Group { get; set; }
        public string VAT_Prod__Posting_Group { get; set; }
        public string Row_Totaling { get; set; }
        public int Amount_Type { get; set; }
        public int Calculate_with { get; set; }
        public byte Print { get; set; }
        public int Print_with { get; set; }
        public byte New_Page { get; set; }
        public string Tax_Jurisdiction_Code { get; set; }
        public byte Use_Tax { get; set; }
    }
}
