//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLINTEC_Ins__Coverage_Ledger_Entry
    {
        public byte[] timestamp { get; set; }
        public int Entry_No_ { get; set; }
        public string Insurance_No_ { get; set; }
        public byte Disposed_FA { get; set; }
        public string FA_No_ { get; set; }
        public string FA_Description { get; set; }
        public System.DateTime Posting_Date { get; set; }
        public int Document_Type { get; set; }
        public System.DateTime Document_Date { get; set; }
        public string Document_No_ { get; set; }
        public string External_Document_No_ { get; set; }
        public decimal Amount { get; set; }
        public string Description { get; set; }
        public string FA_Class_Code { get; set; }
        public string FA_Subclass_Code { get; set; }
        public string FA_Location_Code { get; set; }
        public string Global_Dimension_1_Code { get; set; }
        public string Global_Dimension_2_Code { get; set; }
        public string Location_Code { get; set; }
        public string User_ID { get; set; }
        public string Source_Code { get; set; }
        public string Journal_Batch_Name { get; set; }
        public string Reason_Code { get; set; }
        public byte Index_Entry { get; set; }
        public string No__Series { get; set; }
        public int Dimension_Set_ID { get; set; }
    }
}
