//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLINTEC_Analysis_Report_Name
    {
        public byte[] timestamp { get; set; }
        public int Analysis_Area { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Analysis_Line_Template_Name { get; set; }
        public string Analysis_Column_Template_Name { get; set; }
    }
}
