//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLINTEC_Change_Log_Setup__Table_
    {
        public byte[] timestamp { get; set; }
        public int Table_No_ { get; set; }
        public int Log_Insertion { get; set; }
        public int Log_Modification { get; set; }
        public int Log_Deletion { get; set; }
    }
}
