//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLINTEC_Service_Document_Register
    {
        public byte[] timestamp { get; set; }
        public int Source_Document_Type { get; set; }
        public string Source_Document_No_ { get; set; }
        public int Destination_Document_Type { get; set; }
        public string Destination_Document_No_ { get; set; }
    }
}
