//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLINTEC_Family_Line
    {
        public byte[] timestamp { get; set; }
        public string Family_No_ { get; set; }
        public int Line_No_ { get; set; }
        public string Item_No_ { get; set; }
        public string Description { get; set; }
        public string Description_2 { get; set; }
        public string Unit_of_Measure_Code { get; set; }
        public decimal Quantity { get; set; }
        public int Low_Level_Code { get; set; }
    }
}
