//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLINTEC_Customer_Template
    {
        public byte[] timestamp { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public string Territory_Code { get; set; }
        public string Global_Dimension_1_Code { get; set; }
        public string Global_Dimension_2_Code { get; set; }
        public string Customer_Posting_Group { get; set; }
        public string Currency_Code { get; set; }
        public string Customer_Price_Group { get; set; }
        public string Payment_Terms_Code { get; set; }
        public string Shipment_Method_Code { get; set; }
        public string Invoice_Disc__Code { get; set; }
        public string Customer_Disc__Group { get; set; }
        public string Country_Region_Code { get; set; }
        public string Payment_Method_Code { get; set; }
        public string Gen__Bus__Posting_Group { get; set; }
        public string VAT_Bus__Posting_Group { get; set; }
        public byte Allow_Line_Disc_ { get; set; }
    }
}
