//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLINTEC_Error_Buffer
    {
        public byte[] timestamp { get; set; }
        public int Error_No_ { get; set; }
        public string Error_Text { get; set; }
        public int Source_Table { get; set; }
        public string Source_No_ { get; set; }
        public int Source_Ref__No_ { get; set; }
    }
}
