//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLINTEC_Contact_Profile_Answer
    {
        public byte[] timestamp { get; set; }
        public string Contact_No_ { get; set; }
        public string Profile_Questionnaire_Code { get; set; }
        public int Line_No_ { get; set; }
        public string Contact_Company_No_ { get; set; }
        public int Profile_Questionnaire_Priority { get; set; }
        public int Answer_Priority { get; set; }
        public System.DateTime Last_Date_Updated { get; set; }
        public decimal Questions_Answered____ { get; set; }
    }
}
