//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLINTEC_Item_Tracking_Code
    {
        public byte[] timestamp { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public string Warranty_Date_Formula { get; set; }
        public byte Man__Warranty_Date_Entry_Reqd_ { get; set; }
        public byte Man__Expir__Date_Entry_Reqd_ { get; set; }
        public byte Strict_Expiration_Posting { get; set; }
        public byte SN_Specific_Tracking { get; set; }
        public byte SN_Info__Inbound_Must_Exist { get; set; }
        public byte SN_Info__Outbound_Must_Exist { get; set; }
        public byte SN_Warehouse_Tracking { get; set; }
        public byte SN_Purchase_Inbound_Tracking { get; set; }
        public byte SN_Purchase_Outbound_Tracking { get; set; }
        public byte SN_Sales_Inbound_Tracking { get; set; }
        public byte SN_Sales_Outbound_Tracking { get; set; }
        public byte SN_Pos__Adjmt__Inb__Tracking { get; set; }
        public byte SN_Pos__Adjmt__Outb__Tracking { get; set; }
        public byte SN_Neg__Adjmt__Inb__Tracking { get; set; }
        public byte SN_Neg__Adjmt__Outb__Tracking { get; set; }
        public byte SN_Transfer_Tracking { get; set; }
        public byte SN_Manuf__Inbound_Tracking { get; set; }
        public byte SN_Manuf__Outbound_Tracking { get; set; }
        public byte SN_Assembly_Inbound_Tracking { get; set; }
        public byte SN_Assembly_Outbound_Tracking { get; set; }
        public byte Lot_Specific_Tracking { get; set; }
        public byte Lot_Info__Inbound_Must_Exist { get; set; }
        public byte Lot_Info__Outbound_Must_Exist { get; set; }
        public byte Lot_Warehouse_Tracking { get; set; }
        public byte Lot_Purchase_Inbound_Tracking { get; set; }
        public byte Lot_Purchase_Outbound_Tracking { get; set; }
        public byte Lot_Sales_Inbound_Tracking { get; set; }
        public byte Lot_Sales_Outbound_Tracking { get; set; }
        public byte Lot_Pos__Adjmt__Inb__Tracking { get; set; }
        public byte Lot_Pos__Adjmt__Outb__Tracking { get; set; }
        public byte Lot_Neg__Adjmt__Inb__Tracking { get; set; }
        public byte Lot_Neg__Adjmt__Outb__Tracking { get; set; }
        public byte Lot_Transfer_Tracking { get; set; }
        public byte Lot_Manuf__Inbound_Tracking { get; set; }
        public byte Lot_Manuf__Outbound_Tracking { get; set; }
        public byte Lot_Assembly_Inbound_Tracking { get; set; }
        public byte Lot_Assembly_Outbound_Tracking { get; set; }
    }
}
