//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLINTEC_Item_Availability_Line
    {
        public byte[] timestamp { get; set; }
        public string Name { get; set; }
        public int QuerySource { get; set; }
        public int Table_No_ { get; set; }
        public decimal Quantity { get; set; }
    }
}
