//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLINTEC_Availability_at_Date
    {
        public byte[] timestamp { get; set; }
        public System.DateTime Period_Start { get; set; }
        public decimal Scheduled_Receipt { get; set; }
        public decimal Gross_Requirement { get; set; }
        public System.DateTime Period_End { get; set; }
    }
}
