//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLINTEC_Config__Template_Line
    {
        public byte[] timestamp { get; set; }
        public string Data_Template_Code { get; set; }
        public int Line_No_ { get; set; }
        public int Type { get; set; }
        public int Field_ID { get; set; }
        public string Field_Name { get; set; }
        public int Table_ID { get; set; }
        public string Template_Code { get; set; }
        public byte Mandatory { get; set; }
        public string Reference { get; set; }
        public string Default_Value { get; set; }
        public byte Skip_Relation_Check { get; set; }
        public int Language_ID { get; set; }
    }
}
