//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLINTEC_Inventory_Report_Entry
    {
        public byte[] timestamp { get; set; }
        public int Type { get; set; }
        public int Entry_No_ { get; set; }
        public string No_ { get; set; }
        public decimal Inventory { get; set; }
        public decimal Inventory__Interim_ { get; set; }
        public decimal WIP_Inventory { get; set; }
        public decimal Direct_Cost_Applied_Actual { get; set; }
        public decimal Overhead_Applied_Actual { get; set; }
        public decimal Purchase_Variance { get; set; }
        public decimal Inventory_Adjmt_ { get; set; }
        public decimal Invt__Accrual__Interim_ { get; set; }
        public decimal COGS { get; set; }
        public decimal COGS__Interim_ { get; set; }
        public decimal Material_Variance { get; set; }
        public decimal Capacity_Variance { get; set; }
        public decimal Subcontracted_Variance { get; set; }
        public decimal Capacity_Overhead_Variance { get; set; }
        public decimal Mfg__Overhead_Variance { get; set; }
        public decimal Total { get; set; }
        public decimal G_L_Total { get; set; }
        public decimal Difference { get; set; }
        public decimal Direct_Cost_Applied_WIP { get; set; }
        public decimal Overhead_Applied_WIP { get; set; }
        public decimal Inventory_To_WIP { get; set; }
        public decimal WIP_To_Interim { get; set; }
        public decimal Direct_Cost_Applied { get; set; }
        public decimal Overhead_Applied { get; set; }
        public string Description { get; set; }
        public string Warning { get; set; }
        public byte Cost_is_Posted_to_G_L_Warning { get; set; }
        public byte Expected_Cost_Posting_Warning { get; set; }
        public byte Compression_Warning { get; set; }
        public byte Posting_Group_Warning { get; set; }
        public byte Direct_Postings_Warning { get; set; }
        public byte Posting_Date_Warning { get; set; }
        public byte Closing_Period_Overlap_Warning { get; set; }
        public byte Similar_Accounts_Warning { get; set; }
        public byte Deleted_G_L_Accounts_Warning { get; set; }
    }
}
