//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLINTEC_Service_Ledger_Entry
    {
        public byte[] timestamp { get; set; }
        public int Entry_No_ { get; set; }
        public string Service_Contract_No_ { get; set; }
        public int Document_Type { get; set; }
        public string Document_No_ { get; set; }
        public string Serv__Contract_Acc__Gr__Code { get; set; }
        public int Document_Line_No_ { get; set; }
        public byte Moved_from_Prepaid_Acc_ { get; set; }
        public System.DateTime Posting_Date { get; set; }
        public decimal Amount__LCY_ { get; set; }
        public string Customer_No_ { get; set; }
        public string Ship_to_Code { get; set; }
        public string Item_No___Serviced_ { get; set; }
        public string Serial_No___Serviced_ { get; set; }
        public string User_ID { get; set; }
        public string Contract_Invoice_Period { get; set; }
        public string Global_Dimension_1_Code { get; set; }
        public string Global_Dimension_2_Code { get; set; }
        public string Service_Item_No___Serviced_ { get; set; }
        public string Variant_Code__Serviced_ { get; set; }
        public string Contract_Group_Code { get; set; }
        public int Type { get; set; }
        public string No_ { get; set; }
        public decimal Cost_Amount { get; set; }
        public decimal Discount_Amount { get; set; }
        public decimal Unit_Cost { get; set; }
        public decimal Quantity { get; set; }
        public decimal Charged_Qty_ { get; set; }
        public decimal Unit_Price { get; set; }
        public decimal Discount__ { get; set; }
        public decimal Contract_Disc__Amount { get; set; }
        public string Bill_to_Customer_No_ { get; set; }
        public string Fault_Reason_Code { get; set; }
        public string Description { get; set; }
        public string Service_Order_Type { get; set; }
        public string Service_Order_No_ { get; set; }
        public string Job_No_ { get; set; }
        public string Gen__Bus__Posting_Group { get; set; }
        public string Gen__Prod__Posting_Group { get; set; }
        public string Location_Code { get; set; }
        public string Unit_of_Measure_Code { get; set; }
        public string Work_Type_Code { get; set; }
        public string Bin_Code { get; set; }
        public string Responsibility_Center { get; set; }
        public string Variant_Code { get; set; }
        public int Entry_Type { get; set; }
        public byte Open { get; set; }
        public string Serv__Price_Adjmt__Gr__Code { get; set; }
        public string Service_Price_Group_Code { get; set; }
        public byte Prepaid { get; set; }
        public int Apply_Until_Entry_No_ { get; set; }
        public int Applies_to_Entry_No_ { get; set; }
        public decimal Amount { get; set; }
        public string Job_Task_No_ { get; set; }
        public int Job_Line_Type { get; set; }
        public byte Job_Posted { get; set; }
        public int Dimension_Set_ID { get; set; }
    }
}
