//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLINTEC_XBRL_Line_Constant
    {
        public byte[] timestamp { get; set; }
        public string XBRL_Taxonomy_Name { get; set; }
        public int XBRL_Taxonomy_Line_No_ { get; set; }
        public int Line_No_ { get; set; }
        public System.DateTime Starting_Date { get; set; }
        public decimal Constant_Amount { get; set; }
    }
}
