//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLINTEC_Timeline_Event
    {
        public byte[] timestamp { get; set; }
        public int ID { get; set; }
        public int Transaction_Type { get; set; }
        public string Description { get; set; }
        public System.DateTime Original_Date { get; set; }
        public System.DateTime New_Date { get; set; }
        public string ChangeRefNo { get; set; }
        public byte[] Source_Line_ID { get; set; }
        public byte[] Source_Document_ID { get; set; }
        public decimal Original_Quantity { get; set; }
        public decimal New_Quantity { get; set; }
    }
}
