//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLINTEC_Job
    {
        public byte[] timestamp { get; set; }
        public string No_ { get; set; }
        public string Search_Description { get; set; }
        public string Description { get; set; }
        public string Description_2 { get; set; }
        public string Bill_to_Customer_No_ { get; set; }
        public System.DateTime Creation_Date { get; set; }
        public System.DateTime Starting_Date { get; set; }
        public System.DateTime Ending_Date { get; set; }
        public int Status { get; set; }
        public string Person_Responsible { get; set; }
        public string Global_Dimension_1_Code { get; set; }
        public string Global_Dimension_2_Code { get; set; }
        public string Job_Posting_Group { get; set; }
        public int Blocked { get; set; }
        public System.DateTime Last_Date_Modified { get; set; }
        public string Customer_Disc__Group { get; set; }
        public string Customer_Price_Group { get; set; }
        public string Language_Code { get; set; }
        public byte[] Picture { get; set; }
        public string Bill_to_Name { get; set; }
        public string Bill_to_Address { get; set; }
        public string Bill_to_Address_2 { get; set; }
        public string Bill_to_City { get; set; }
        public string Bill_to_County { get; set; }
        public string Bill_to_Post_Code { get; set; }
        public string No__Series { get; set; }
        public string Bill_to_Country_Region_Code { get; set; }
        public string Bill_to_Name_2 { get; set; }
        public int Reserve { get; set; }
        public string WIP_Method { get; set; }
        public string Currency_Code { get; set; }
        public string Bill_to_Contact_No_ { get; set; }
        public string Bill_to_Contact { get; set; }
        public System.DateTime WIP_Posting_Date { get; set; }
        public string Invoice_Currency_Code { get; set; }
        public int Exch__Calculation__Cost_ { get; set; }
        public int Exch__Calculation__Price_ { get; set; }
        public byte Allow_Schedule_Contract_Lines { get; set; }
        public byte Complete { get; set; }
        public byte Apply_Usage_Link { get; set; }
        public int WIP_Posting_Method { get; set; }
    }
}
