//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLINTEC_Planning_Buffer
    {
        public byte[] timestamp { get; set; }
        public int Buffer_No_ { get; set; }
        public System.DateTime Date { get; set; }
        public int Document_Type { get; set; }
        public string Document_No_ { get; set; }
        public string Item_No_ { get; set; }
        public string Description { get; set; }
        public decimal Gross_Requirement { get; set; }
        public decimal Planned_Receipts { get; set; }
        public decimal Scheduled_Receipts { get; set; }
    }
}
