//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLINTEC_Job_Task_Dimension
    {
        public byte[] timestamp { get; set; }
        public string Job_No_ { get; set; }
        public string Job_Task_No_ { get; set; }
        public string Dimension_Code { get; set; }
        public string Dimension_Value_Code { get; set; }
        public int Multiple_Selection_Action { get; set; }
    }
}
