//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLINTEC_Production_BOM_Comment_Line
    {
        public byte[] timestamp { get; set; }
        public string Production_BOM_No_ { get; set; }
        public int BOM_Line_No_ { get; set; }
        public string Version_Code { get; set; }
        public int Line_No_ { get; set; }
        public System.DateTime Date { get; set; }
        public string Comment { get; set; }
        public string Code { get; set; }
    }
}
