//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLINTEC_Direct_Debit_Collection_Entry
    {
        public byte[] timestamp { get; set; }
        public int Direct_Debit_Collection_No_ { get; set; }
        public int Entry_No_ { get; set; }
        public string Customer_No_ { get; set; }
        public int Applies_to_Entry_No_ { get; set; }
        public System.DateTime Transfer_Date { get; set; }
        public string Currency_Code { get; set; }
        public decimal Transfer_Amount { get; set; }
        public string Transaction_ID { get; set; }
        public int Sequence_Type { get; set; }
        public int Status { get; set; }
        public string Mandate_ID { get; set; }
    }
}
