//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLINTEC_XBRL_Taxonomy
    {
        public byte[] timestamp { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string xmlns_xbrli { get; set; }
        public string targetNamespace { get; set; }
        public string schemaLocation { get; set; }
    }
}
