//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLINTEC_Matrix_Cost_Center_Mapping
    {
        public byte[] timestamp { get; set; }
        public string Matrix_Cost_Center { get; set; }
        public string NAV_Cost_Center { get; set; }
        public string Reason_Code { get; set; }
    }
}
