//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLINTEC_Delivery_Sorter
    {
        public byte[] timestamp { get; set; }
        public int No_ { get; set; }
        public int Attachment_No_ { get; set; }
        public int Correspondence_Type { get; set; }
        public string Subject { get; set; }
        public byte Send_Word_Docs__as_Attmt_ { get; set; }
        public string Language_Code { get; set; }
    }
}
