//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLINTEC_Warehouse_Source_Filter
    {
        public byte[] timestamp { get; set; }
        public int Type { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public string Item_No__Filter { get; set; }
        public string Variant_Code_Filter { get; set; }
        public string Unit_of_Measure_Filter { get; set; }
        public string Sell_to_Customer_No__Filter { get; set; }
        public string Buy_from_Vendor_No__Filter { get; set; }
        public string Customer_No__Filter { get; set; }
        public string Shipment_Method_Code_Filter { get; set; }
        public string Shipping_Agent_Code_Filter { get; set; }
        public string Shipping_Advice_Filter { get; set; }
        public byte Do_Not_Fill_Qty__to_Handle { get; set; }
        public byte Show_Filter_Request { get; set; }
        public string Shipping_Agent_Service_Filter { get; set; }
        public string In_Transit_Code_Filter { get; set; }
        public string Transfer_from_Code_Filter { get; set; }
        public string Transfer_to_Code_Filter { get; set; }
        public string Source_No__Filter { get; set; }
        public string Source_Document { get; set; }
        public byte Sales_Orders { get; set; }
        public byte Sales_Return_Orders { get; set; }
        public byte Purchase_Orders { get; set; }
        public byte Purchase_Return_Orders { get; set; }
        public byte Inbound_Transfers { get; set; }
        public byte Outbound_Transfers { get; set; }
        public byte Partial { get; set; }
        public byte Complete { get; set; }
        public byte Service_Orders { get; set; }
        public string Planned_Delivery_Date { get; set; }
        public string Planned_Shipment_Date { get; set; }
        public string Planned_Receipt_Date { get; set; }
        public string Expected_Receipt_Date { get; set; }
        public string Shipment_Date { get; set; }
        public string Receipt_Date { get; set; }
        public string Sales_Shipment_Date { get; set; }
    }
}
