//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLINTEC_Service_Cost
    {
        public byte[] timestamp { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public string Account_No_ { get; set; }
        public decimal Default_Unit_Price { get; set; }
        public decimal Default_Quantity { get; set; }
        public string Unit_of_Measure_Code { get; set; }
        public int Cost_Type { get; set; }
        public string Service_Zone_Code { get; set; }
        public decimal Default_Unit_Cost { get; set; }
    }
}
