//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLINTEC_XBRL_Taxonomy_Line
    {
        public byte[] timestamp { get; set; }
        public string XBRL_Taxonomy_Name { get; set; }
        public int Line_No_ { get; set; }
        public string Name { get; set; }
        public int Level { get; set; }
        public int Source_Type { get; set; }
        public decimal Constant_Amount { get; set; }
        public string Description { get; set; }
        public string XBRL_Item_Type { get; set; }
        public int Parent_Line_No_ { get; set; }
        public int XBRL_Schema_Line_No_ { get; set; }
        public string Presentation_Order { get; set; }
        public int Presentation_Order_No_ { get; set; }
        public string Element_ID { get; set; }
        public int Numeric_Context_Period_Type { get; set; }
        public int Presentation_Linkbase_Line_No_ { get; set; }
        public byte Type_Description_Element { get; set; }
    }
}
