//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLINTEC_Currency_Exchange_Rate
    {
        public byte[] timestamp { get; set; }
        public string Currency_Code { get; set; }
        public System.DateTime Starting_Date { get; set; }
        public decimal Exchange_Rate_Amount { get; set; }
        public decimal Adjustment_Exch__Rate_Amount { get; set; }
        public string Relational_Currency_Code { get; set; }
        public decimal Relational_Exch__Rate_Amount { get; set; }
        public int Fix_Exchange_Rate_Amount { get; set; }
        public decimal Relational_Adjmt_Exch_Rate_Amt { get; set; }
    }
}
