//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLINTEC_Resource_Location
    {
        public byte[] timestamp { get; set; }
        public string Location_Code { get; set; }
        public System.DateTime Starting_Date { get; set; }
        public string Resource_No_ { get; set; }
    }
}
