//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLINTEC_Bank_Account_Ledger_Entry
    {
        public byte[] timestamp { get; set; }
        public int Entry_No_ { get; set; }
        public string Bank_Account_No_ { get; set; }
        public System.DateTime Posting_Date { get; set; }
        public int Document_Type { get; set; }
        public string Document_No_ { get; set; }
        public string Description { get; set; }
        public string Currency_Code { get; set; }
        public decimal Amount { get; set; }
        public decimal Remaining_Amount { get; set; }
        public decimal Amount__LCY_ { get; set; }
        public string Bank_Acc__Posting_Group { get; set; }
        public string Global_Dimension_1_Code { get; set; }
        public string Global_Dimension_2_Code { get; set; }
        public string Our_Contact_Code { get; set; }
        public string User_ID { get; set; }
        public string Source_Code { get; set; }
        public byte Open { get; set; }
        public byte Positive { get; set; }
        public int Closed_by_Entry_No_ { get; set; }
        public System.DateTime Closed_at_Date { get; set; }
        public string Journal_Batch_Name { get; set; }
        public string Reason_Code { get; set; }
        public int Bal__Account_Type { get; set; }
        public string Bal__Account_No_ { get; set; }
        public int Transaction_No_ { get; set; }
        public int Statement_Status { get; set; }
        public string Statement_No_ { get; set; }
        public int Statement_Line_No_ { get; set; }
        public decimal Debit_Amount { get; set; }
        public decimal Credit_Amount { get; set; }
        public decimal Debit_Amount__LCY_ { get; set; }
        public decimal Credit_Amount__LCY_ { get; set; }
        public System.DateTime Document_Date { get; set; }
        public string External_Document_No_ { get; set; }
        public byte Reversed { get; set; }
        public int Reversed_by_Entry_No_ { get; set; }
        public int Reversed_Entry_No_ { get; set; }
        public int Dimension_Set_ID { get; set; }
    }
}
