//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class issue_occurrence
    {
        public int issue_occurrence_id { get; set; }
        public Nullable<System.DateTime> date_time { get; set; }
        public string material_id { get; set; }
        public string description { get; set; }
        public string machine_machine_id { get; set; }
        public Nullable<int> line_line_id { get; set; }
        public Nullable<int> issue_issue_ID { get; set; }
        public Nullable<int> responsible_person_emp_id { get; set; }
        public string issue_satus { get; set; }
        public string location { get; set; }
        public Nullable<int> responsible_person_confirm_status { get; set; }
        public string responsible_person_confirm_feedback { get; set; }
        public string date { get; set; }
        public virtual issue issue { get; set; }
    }
}
