//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class notification_handling
    {
        public int issue_occurrence_id { get; set; }
        public string EmployeeNumber { get; set; }
        public Nullable<int> notification_status { get; set; }
    }
}
