//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission_Set
    {
        public byte[] timestamp { get; set; }
        public string Role_ID { get; set; }
        public string Name { get; set; }
        public string Activity_Description { get; set; }
    }
}
