//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Record_Link
    {
        public byte[] timestamp { get; set; }
        public int Link_ID { get; set; }
        public byte[] Record_ID { get; set; }
        public string URL1 { get; set; }
        public string URL2 { get; set; }
        public string URL3 { get; set; }
        public string URL4 { get; set; }
        public string Description { get; set; }
        public int Type { get; set; }
        public byte[] Note { get; set; }
        public System.DateTime Created { get; set; }
        public string User_ID { get; set; }
        public string Company { get; set; }
        public byte Notify { get; set; }
        public string To_User_ID { get; set; }
    }
}
