//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report_List_Translation
    {
        public byte[] timestamp { get; set; }
        public int Menu_ID { get; set; }
        public int Line_No_ { get; set; }
        public int Language_ID { get; set; }
        public string Description { get; set; }
    }
}
