//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session_Event
    {
        public byte[] timestamp { get; set; }
        public System.Guid User_SID { get; set; }
        public int Server_Instance_ID { get; set; }
        public int Session_ID { get; set; }
        public System.DateTime Event_Datetime { get; set; }
        public int Event_Type { get; set; }
        public int Client_Type { get; set; }
        public string Database_Name { get; set; }
        public string Client_Computer_Name { get; set; }
        public string User_ID { get; set; }
        public string Comment { get; set; }
    }
}
