//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRAINTEC_Shipping_Agent_Services
    {
        public byte[] timestamp { get; set; }
        public string Shipping_Agent_Code { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public string Shipping_Time { get; set; }
        public string Base_Calendar_Code { get; set; }
    }
}
