//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRAINTEC_Source_Code_Setup
    {
        public byte[] timestamp { get; set; }
        public string Primary_Key { get; set; }
        public string Sales { get; set; }
        public string Purchases { get; set; }
        public string Inventory_Post_Cost { get; set; }
        public string Exchange_Rate_Adjmt_ { get; set; }
        public string Post_Recognition { get; set; }
        public string Post_Value { get; set; }
        public string Close_Income_Statement { get; set; }
        public string Consolidation { get; set; }
        public string General_Journal { get; set; }
        public string Sales_Journal { get; set; }
        public string Purchase_Journal { get; set; }
        public string Cash_Receipt_Journal { get; set; }
        public string Payment_Journal { get; set; }
        public string Item_Journal { get; set; }
        public string Resource_Journal { get; set; }
        public string Job_Journal { get; set; }
        public string Sales_Entry_Application { get; set; }
        public string Purchase_Entry_Application { get; set; }
        public string VAT_Settlement { get; set; }
        public string Compress_G_L { get; set; }
        public string Compress_VAT_Entries { get; set; }
        public string Compress_Cust__Ledger { get; set; }
        public string Compress_Vend__Ledger { get; set; }
        public string Compress_Item_Ledger { get; set; }
        public string Compress_Res__Ledger { get; set; }
        public string Compress_Job_Ledger { get; set; }
        public string Item_Reclass__Journal { get; set; }
        public string Phys__Inventory_Journal { get; set; }
        public string Compress_Bank_Acc__Ledger { get; set; }
        public string Compress_Check_Ledger { get; set; }
        public string Financially_Voided_Check { get; set; }
        public string Finance_Charge_Memo { get; set; }
        public string Reminder { get; set; }
        public string Deleted_Document { get; set; }
        public string Adjust_Add__Reporting_Currency { get; set; }
        public string Trans__Bank_Rec__to_Gen__Jnl_ { get; set; }
        public string IC_General_Journal { get; set; }
        public string Unapplied_Sales_Entry_Appln_ { get; set; }
        public string Unapplied_Purch__Entry_Appln_ { get; set; }
        public string Reversal { get; set; }
        public string Cash_Flow_Worksheet { get; set; }
        public string Assembly { get; set; }
        public string Job_G_L_Journal { get; set; }
        public string Job_G_L_WIP { get; set; }
        public string G_L_Entry_to_CA { get; set; }
        public string Cost_Journal { get; set; }
        public string Cost_Allocation { get; set; }
        public string Transfer_Budget_to_Actual { get; set; }
        public string Consumption_Journal { get; set; }
        public string Output_Journal { get; set; }
        public string Flushing { get; set; }
        public string Capacity_Journal { get; set; }
        public string Production_Journal { get; set; }
        public string Fixed_Asset_Journal { get; set; }
        public string Fixed_Asset_G_L_Journal { get; set; }
        public string Insurance_Journal { get; set; }
        public string Compress_FA_Ledger { get; set; }
        public string Compress_Maintenance_Ledger { get; set; }
        public string Compress_Insurance_Ledger { get; set; }
        public string Transfer { get; set; }
        public string Revaluation_Journal { get; set; }
        public string Adjust_Cost { get; set; }
        public string Service_Management { get; set; }
        public string Compress_Item_Budget { get; set; }
        public string Whse__Item_Journal { get; set; }
        public string Whse__Phys__Invt__Journal { get; set; }
        public string Whse__Reclassification_Journal { get; set; }
        public string Whse__Put_away { get; set; }
        public string Whse__Pick { get; set; }
        public string Whse__Movement { get; set; }
        public string Compress_Whse__Entries { get; set; }
    }
}
