//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRAINTEC_Purchase_Discrepancy
    {
        public byte[] timestamp { get; set; }
        public string Purch__Rcpt__No_ { get; set; }
        public int Receipt_Line_No_ { get; set; }
        public string Purchase_Order_No_ { get; set; }
        public string Vendor_No_ { get; set; }
        public byte Discrepancy { get; set; }
        public System.DateTime Discrepancy_Marked_Date { get; set; }
        public string Comment { get; set; }
        public byte Descrepancy_Reversed { get; set; }
        public System.DateTime Reversed_Date { get; set; }
        public string Reason_for_Reversing { get; set; }
        public string No_ { get; set; }
        public string Description { get; set; }
        public int Type { get; set; }
        public string GRN_Invoice_No_ { get; set; }
        public System.DateTime Posting_Date { get; set; }
        public decimal Quantity { get; set; }
    }
}
