//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRAINTEC_Cost_Element_Buffer
    {
        public byte[] timestamp { get; set; }
        public int Type { get; set; }
        public int Variance_Type { get; set; }
        public decimal Actual_Cost { get; set; }
        public decimal Actual_Cost__ACY_ { get; set; }
        public decimal Rounding_Residual { get; set; }
        public decimal Rounding_Residual__ACY_ { get; set; }
        public decimal Expected_Cost { get; set; }
        public decimal Expected_Cost__ACY_ { get; set; }
        public decimal Invoiced_Quantity { get; set; }
        public decimal Remaining_Quantity { get; set; }
        public byte Inbound_Completely_Invoiced { get; set; }
        public int Last_Valid_Value_Entry_No { get; set; }
    }
}
