//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRAINTEC_Production_Forecast_Entry
    {
        public byte[] timestamp { get; set; }
        public int Entry_No_ { get; set; }
        public string Production_Forecast_Name { get; set; }
        public string Item_No_ { get; set; }
        public System.DateTime Forecast_Date { get; set; }
        public decimal Forecast_Quantity { get; set; }
        public string Unit_of_Measure_Code { get; set; }
        public decimal Qty__per_Unit_of_Measure { get; set; }
        public decimal Forecast_Quantity__Base_ { get; set; }
        public string Location_Code { get; set; }
        public byte Component_Forecast { get; set; }
        public string Description { get; set; }
    }
}
