//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRAINTEC_Planning_Assignment
    {
        public byte[] timestamp { get; set; }
        public string Item_No_ { get; set; }
        public string Variant_Code { get; set; }
        public string Location_Code { get; set; }
        public System.DateTime Latest_Date { get; set; }
        public byte Inactive { get; set; }
        public byte Action_Msg__Response_Planning { get; set; }
        public byte Net_Change_Planning { get; set; }
    }
}
