//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRAINTEC_Incoming_Document
    {
        public byte[] timestamp { get; set; }
        public int Entry_No_ { get; set; }
        public string Description { get; set; }
        public System.DateTime Created_Date_Time { get; set; }
        public System.Guid Created_By_User_ID { get; set; }
        public byte Approved { get; set; }
        public System.DateTime Approved_Date_Time { get; set; }
        public System.Guid Approved_By_User_ID { get; set; }
        public System.DateTime Last_Date_Time_Modified { get; set; }
        public System.Guid Last_Modified_By_User_ID { get; set; }
        public byte Posted { get; set; }
        public System.DateTime Posted_Date_Time { get; set; }
        public int Posted_Document_Type { get; set; }
        public string Document_No_ { get; set; }
        public System.DateTime Posting_Date { get; set; }
        public int Status { get; set; }
        public string URL1 { get; set; }
        public string URL2 { get; set; }
        public string URL3 { get; set; }
        public string URL4 { get; set; }
    }
}
