//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRAINTEC_Jobs_Setup
    {
        public byte[] timestamp { get; set; }
        public string Primary_Key { get; set; }
        public string Job_Nos_ { get; set; }
        public byte Apply_Usage_Link_by_Default { get; set; }
        public string Default_WIP_Method { get; set; }
        public string Default_Job_Posting_Group { get; set; }
        public int Default_WIP_Posting_Method { get; set; }
        public byte Automatic_Update_Job_Item_Cost { get; set; }
    }
}
