//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRAINTEC_Vendor_Posting_Group
    {
        public byte[] timestamp { get; set; }
        public string Code { get; set; }
        public string Payables_Account { get; set; }
        public string Service_Charge_Acc_ { get; set; }
        public string Payment_Disc__Debit_Acc_ { get; set; }
        public string Invoice_Rounding_Account { get; set; }
        public string Debit_Curr__Appln__Rndg__Acc_ { get; set; }
        public string Credit_Curr__Appln__Rndg__Acc_ { get; set; }
        public string Debit_Rounding_Account { get; set; }
        public string Credit_Rounding_Account { get; set; }
        public string Payment_Disc__Credit_Acc_ { get; set; }
        public string Payment_Tolerance_Debit_Acc_ { get; set; }
        public string Payment_Tolerance_Credit_Acc_ { get; set; }
    }
}
