//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRAINTEC_Segment_Line
    {
        public byte[] timestamp { get; set; }
        public string Segment_No_ { get; set; }
        public int Line_No_ { get; set; }
        public string Contact_No_ { get; set; }
        public string Campaign_No_ { get; set; }
        public string Salesperson_Code { get; set; }
        public int Correspondence_Type { get; set; }
        public string Interaction_Template_Code { get; set; }
        public decimal Cost__LCY_ { get; set; }
        public decimal Duration__Min__ { get; set; }
        public int Attachment_No_ { get; set; }
        public byte Campaign_Response { get; set; }
        public int Information_Flow { get; set; }
        public int Initiated_By { get; set; }
        public string Contact_Alt__Address_Code { get; set; }
        public int Evaluation { get; set; }
        public byte Campaign_Target { get; set; }
        public string Language_Code { get; set; }
        public string Description { get; set; }
        public System.DateTime Date { get; set; }
        public System.DateTime Time_of_Interaction { get; set; }
        public byte Attempt_Failed { get; set; }
        public string To_do_No_ { get; set; }
        public string Contact_Company_No_ { get; set; }
        public int Campaign_Entry_No_ { get; set; }
        public string Interaction_Group_Code { get; set; }
        public int Document_Type { get; set; }
        public string Document_No_ { get; set; }
        public byte Send_Word_Doc__As_Attmt_ { get; set; }
        public string Contact_Via { get; set; }
        public int Version_No_ { get; set; }
        public int Doc__No__Occurrence { get; set; }
        public string Subject { get; set; }
        public string Opportunity_No_ { get; set; }
        public int Wizard_Step { get; set; }
        public string Wizard_Contact_Name { get; set; }
        public string Opportunity_Description { get; set; }
        public string Campaign_Description { get; set; }
        public byte Interaction_Successful { get; set; }
        public byte Dial_Contact { get; set; }
        public byte Mail_Contact { get; set; }
    }
}
