//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRAINTEC_Prepayment_Inv__Line_Buffer
    {
        public byte[] timestamp { get; set; }
        public string G_L_Account_No_ { get; set; }
        public string Job_No_ { get; set; }
        public string Tax_Area_Code { get; set; }
        public byte Tax_Liable { get; set; }
        public string Tax_Group_Code { get; set; }
        public byte Invoice_Rounding { get; set; }
        public byte Adjustment { get; set; }
        public int Line_No_ { get; set; }
        public int Dimension_Set_ID { get; set; }
        public decimal Amount { get; set; }
        public string Description { get; set; }
        public string Gen__Bus__Posting_Group { get; set; }
        public string Gen__Prod__Posting_Group { get; set; }
        public string VAT_Bus__Posting_Group { get; set; }
        public string VAT_Prod__Posting_Group { get; set; }
        public decimal VAT_Amount { get; set; }
        public int VAT_Calculation_Type { get; set; }
        public decimal VAT_Base_Amount { get; set; }
        public decimal Amount__ACY_ { get; set; }
        public decimal VAT_Amount__ACY_ { get; set; }
        public decimal VAT_Base_Amount__ACY_ { get; set; }
        public decimal VAT_Difference { get; set; }
        public decimal VAT__ { get; set; }
        public string VAT_Identifier { get; set; }
        public string Global_Dimension_1_Code { get; set; }
        public string Global_Dimension_2_Code { get; set; }
        public decimal Amount_Incl__VAT { get; set; }
    }
}
