//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRAINTEC_FA_Journal_Setup
    {
        public byte[] timestamp { get; set; }
        public string Depreciation_Book_Code { get; set; }
        public string User_ID { get; set; }
        public string FA_Jnl__Template_Name { get; set; }
        public string FA_Jnl__Batch_Name { get; set; }
        public string Gen__Jnl__Template_Name { get; set; }
        public string Gen__Jnl__Batch_Name { get; set; }
        public string Insurance_Jnl__Template_Name { get; set; }
        public string Insurance_Jnl__Batch_Name { get; set; }
    }
}
