//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRAINTEC_Analysis_Selected_Dimension
    {
        public byte[] timestamp { get; set; }
        public string User_ID { get; set; }
        public int Object_Type { get; set; }
        public int Object_ID { get; set; }
        public int Analysis_Area { get; set; }
        public string Analysis_View_Code { get; set; }
        public string Dimension_Code { get; set; }
        public string New_Dimension_Value_Code { get; set; }
        public string Dimension_Value_Filter { get; set; }
        public int Level { get; set; }
    }
}
