//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRAINTEC_Item_Ledger_Entry
    {
        public byte[] timestamp { get; set; }
        public int Entry_No_ { get; set; }
        public string Item_No_ { get; set; }
        public System.DateTime Posting_Date { get; set; }
        public int Entry_Type { get; set; }
        public string Source_No_ { get; set; }
        public string Document_No_ { get; set; }
        public string Description { get; set; }
        public string Location_Code { get; set; }
        public decimal Quantity { get; set; }
        public decimal Remaining_Quantity { get; set; }
        public decimal Invoiced_Quantity { get; set; }
        public int Applies_to_Entry { get; set; }
        public byte Open { get; set; }
        public string Global_Dimension_1_Code { get; set; }
        public string Global_Dimension_2_Code { get; set; }
        public byte Positive { get; set; }
        public int Source_Type { get; set; }
        public byte Drop_Shipment { get; set; }
        public string Transaction_Type { get; set; }
        public string Transport_Method { get; set; }
        public string Country_Region_Code { get; set; }
        public string Entry_Exit_Point { get; set; }
        public System.DateTime Document_Date { get; set; }
        public string External_Document_No_ { get; set; }
        public string Area { get; set; }
        public string Transaction_Specification { get; set; }
        public string No__Series { get; set; }
        public int Document_Type { get; set; }
        public int Document_Line_No_ { get; set; }
        public int Order_Type { get; set; }
        public string Order_No_ { get; set; }
        public int Order_Line_No_ { get; set; }
        public int Dimension_Set_ID { get; set; }
        public byte Assemble_to_Order { get; set; }
        public string Job_No_ { get; set; }
        public string Job_Task_No_ { get; set; }
        public byte Job_Purchase { get; set; }
        public string Variant_Code { get; set; }
        public decimal Qty__per_Unit_of_Measure { get; set; }
        public string Unit_of_Measure_Code { get; set; }
        public byte Derived_from_Blanket_Order { get; set; }
        public string Cross_Reference_No_ { get; set; }
        public string Originally_Ordered_No_ { get; set; }
        public string Originally_Ordered_Var__Code { get; set; }
        public byte Out_of_Stock_Substitution { get; set; }
        public string Item_Category_Code { get; set; }
        public byte Nonstock { get; set; }
        public string Purchasing_Code { get; set; }
        public string Product_Group_Code { get; set; }
        public byte Completely_Invoiced { get; set; }
        public System.DateTime Last_Invoice_Date { get; set; }
        public byte Applied_Entry_to_Adjust { get; set; }
        public byte Correction { get; set; }
        public decimal Shipped_Qty__Not_Returned { get; set; }
        public int Prod__Order_Comp__Line_No_ { get; set; }
        public string Serial_No_ { get; set; }
        public string Lot_No_ { get; set; }
        public System.DateTime Warranty_Date { get; set; }
        public System.DateTime Expiration_Date { get; set; }
        public int Item_Tracking { get; set; }
        public string Return_Reason_Code { get; set; }
        public string Reason_Code { get; set; }
    }
}
