//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRAINTEC_Untracked_Planning_Element
    {
        public byte[] timestamp { get; set; }
        public string Worksheet_Template_Name { get; set; }
        public string Worksheet_Batch_Name { get; set; }
        public int Worksheet_Line_No_ { get; set; }
        public int Track_Line_No_ { get; set; }
        public string Item_No_ { get; set; }
        public string Variant_Code { get; set; }
        public string Location_Code { get; set; }
        public int Source_Type { get; set; }
        public string Source_ID { get; set; }
        public decimal Parameter_Value { get; set; }
        public decimal Untracked_Quantity { get; set; }
        public decimal Track_Quantity_From { get; set; }
        public decimal Track_Quantity_To { get; set; }
        public string Source { get; set; }
        public int Warning_Level { get; set; }
    }
}
