//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRAINTEC_Routing_Header
    {
        public byte[] timestamp { get; set; }
        public string No_ { get; set; }
        public string Description { get; set; }
        public string Description_2 { get; set; }
        public string Search_Description { get; set; }
        public System.DateTime Last_Date_Modified { get; set; }
        public int Status { get; set; }
        public int Type { get; set; }
        public string Version_Nos_ { get; set; }
        public string No__Series { get; set; }
        public byte Subcontracted { get; set; }
    }
}
