//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRAINTEC_Job_WIP_Total
    {
        public byte[] timestamp { get; set; }
        public int Entry_No_ { get; set; }
        public string Job_No_ { get; set; }
        public string Job_Task_No_ { get; set; }
        public string WIP_Method { get; set; }
        public System.DateTime WIP_Posting_Date { get; set; }
        public string WIP_Posting_Date_Filter { get; set; }
        public string WIP_Planning_Date_Filter { get; set; }
        public byte Posted_to_G_L { get; set; }
        public decimal Schedule__Total_Cost_ { get; set; }
        public decimal Schedule__Total_Price_ { get; set; }
        public decimal Usage__Total_Cost_ { get; set; }
        public decimal Usage__Total_Price_ { get; set; }
        public decimal Contract__Total_Cost_ { get; set; }
        public decimal Contract__Total_Price_ { get; set; }
        public decimal Contract__Invoiced_Price_ { get; set; }
        public decimal Contract__Invoiced_Cost_ { get; set; }
        public decimal Calc__Recog__Sales_Amount { get; set; }
        public decimal Calc__Recog__Costs_Amount { get; set; }
        public decimal Cost_Completion__ { get; set; }
        public decimal Invoiced__ { get; set; }
    }
}
