//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRAINTEC_Config__Package_Record
    {
        public byte[] timestamp { get; set; }
        public string Package_Code { get; set; }
        public int Table_ID { get; set; }
        public int No_ { get; set; }
        public byte Invalid { get; set; }
    }
}
