//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRAINTEC_Planning_Error_Log
    {
        public byte[] timestamp { get; set; }
        public string Worksheet_Template_Name { get; set; }
        public string Journal_Batch_Name { get; set; }
        public int Entry_No_ { get; set; }
        public string Item_No_ { get; set; }
        public string Error_Description { get; set; }
        public int Table_ID { get; set; }
        public string Table_Position { get; set; }
    }
}
