//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRAINTEC_Serv__Price_Group_Setup
    {
        public byte[] timestamp { get; set; }
        public string Service_Price_Group_Code { get; set; }
        public string Fault_Area_Code { get; set; }
        public string Cust__Price_Group_Code { get; set; }
        public string Currency_Code { get; set; }
        public System.DateTime Starting_Date { get; set; }
        public string Serv__Price_Adjmt__Gr__Code { get; set; }
        public byte Include_Discounts { get; set; }
        public int Adjustment_Type { get; set; }
        public decimal Amount { get; set; }
        public byte Include_VAT { get; set; }
    }
}
