//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRAINTEC_Config__Selection
    {
        public byte[] timestamp { get; set; }
        public int Line_No_ { get; set; }
        public int Table_ID { get; set; }
        public string Name { get; set; }
        public int Line_Type { get; set; }
        public int Parent_Line_No_ { get; set; }
        public byte Selected { get; set; }
        public int Vertical_Sorting { get; set; }
    }
}
