//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRAINTEC_DO_Payment_Connection_Details
    {
        public byte[] timestamp { get; set; }
        public string Primary_Key { get; set; }
        public byte[] UserName { get; set; }
        public byte[] Password { get; set; }
    }
}
