//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRAINTEC_BOM_Component
    {
        public byte[] timestamp { get; set; }
        public string Parent_Item_No_ { get; set; }
        public int Line_No_ { get; set; }
        public int Type { get; set; }
        public string No_ { get; set; }
        public string Description { get; set; }
        public string Unit_of_Measure_Code { get; set; }
        public decimal Quantity_per { get; set; }
        public string Position { get; set; }
        public string Position_2 { get; set; }
        public string Position_3 { get; set; }
        public string Machine_No_ { get; set; }
        public string Lead_Time_Offset { get; set; }
        public int Resource_Usage_Type { get; set; }
        public string Variant_Code { get; set; }
        public int Installed_in_Line_No_ { get; set; }
        public string Installed_in_Item_No_ { get; set; }
    }
}
