//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRAINTEC_Warehouse_Shipment_Header
    {
        public byte[] timestamp { get; set; }
        public string No_ { get; set; }
        public string Location_Code { get; set; }
        public string Assigned_User_ID { get; set; }
        public System.DateTime Assignment_Date { get; set; }
        public System.DateTime Assignment_Time { get; set; }
        public int Sorting_Method { get; set; }
        public string No__Series { get; set; }
        public string Bin_Code { get; set; }
        public string Zone_Code { get; set; }
        public int Document_Status { get; set; }
        public System.DateTime Posting_Date { get; set; }
        public string Shipping_Agent_Code { get; set; }
        public string Shipping_Agent_Service_Code { get; set; }
        public string Shipment_Method_Code { get; set; }
        public System.DateTime Shipment_Date { get; set; }
        public int Status { get; set; }
        public string External_Document_No_ { get; set; }
        public byte Create_Posted_Header { get; set; }
        public string Shipping_No_ { get; set; }
        public string Last_Shipping_No_ { get; set; }
        public string Shipping_No__Series { get; set; }
    }
}
