//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRAINTEC_Item
    {
        public byte[] timestamp { get; set; }
        public string No_ { get; set; }
        public string No__2 { get; set; }
        public string Description { get; set; }
        public string Search_Description { get; set; }
        public string Description_2 { get; set; }
        public string Base_Unit_of_Measure { get; set; }
        public int Price_Unit_Conversion { get; set; }
        public int Type { get; set; }
        public string Inventory_Posting_Group { get; set; }
        public string Shelf_No_ { get; set; }
        public string Item_Disc__Group { get; set; }
        public byte Allow_Invoice_Disc_ { get; set; }
        public int Statistics_Group { get; set; }
        public int Commission_Group { get; set; }
        public decimal Unit_Price { get; set; }
        public int Price_Profit_Calculation { get; set; }
        public decimal Profit__ { get; set; }
        public int Costing_Method { get; set; }
        public decimal Unit_Cost { get; set; }
        public decimal Standard_Cost { get; set; }
        public decimal Last_Direct_Cost { get; set; }
        public decimal Indirect_Cost__ { get; set; }
        public byte Cost_is_Adjusted { get; set; }
        public byte Allow_Online_Adjustment { get; set; }
        public string Vendor_No_ { get; set; }
        public string Vendor_Item_No_ { get; set; }
        public string Lead_Time_Calculation { get; set; }
        public decimal Reorder_Point { get; set; }
        public decimal Maximum_Inventory { get; set; }
        public decimal Reorder_Quantity { get; set; }
        public string Alternative_Item_No_ { get; set; }
        public decimal Unit_List_Price { get; set; }
        public decimal Duty_Due__ { get; set; }
        public string Duty_Code { get; set; }
        public decimal Gross_Weight { get; set; }
        public decimal Net_Weight { get; set; }
        public decimal Units_per_Parcel { get; set; }
        public decimal Unit_Volume { get; set; }
        public string Durability { get; set; }
        public string Freight_Type { get; set; }
        public string Tariff_No_ { get; set; }
        public decimal Duty_Unit_Conversion { get; set; }
        public string Country_Region_Purchased_Code { get; set; }
        public decimal Budget_Quantity { get; set; }
        public decimal Budgeted_Amount { get; set; }
        public decimal Budget_Profit { get; set; }
        public byte Blocked { get; set; }
        public System.DateTime Last_Date_Modified { get; set; }
        public byte Price_Includes_VAT { get; set; }
        public string VAT_Bus__Posting_Gr___Price_ { get; set; }
        public string Gen__Prod__Posting_Group { get; set; }
        public byte[] Picture { get; set; }
        public string Country_Region_of_Origin_Code { get; set; }
        public byte Automatic_Ext__Texts { get; set; }
        public string No__Series { get; set; }
        public string Tax_Group_Code { get; set; }
        public string VAT_Prod__Posting_Group { get; set; }
        public int Reserve { get; set; }
        public string Global_Dimension_1_Code { get; set; }
        public string Global_Dimension_2_Code { get; set; }
        public int Stockout_Warning { get; set; }
        public int Prevent_Negative_Inventory { get; set; }
        public string Application_Wksh__User_ID { get; set; }
        public int Assembly_Policy { get; set; }
        public int Low_Level_Code { get; set; }
        public decimal Lot_Size { get; set; }
        public string Serial_Nos_ { get; set; }
        public System.DateTime Last_Unit_Cost_Calc__Date { get; set; }
        public decimal Rolled_up_Material_Cost { get; set; }
        public decimal Rolled_up_Capacity_Cost { get; set; }
        public decimal Scrap__ { get; set; }
        public byte Inventory_Value_Zero { get; set; }
        public int Discrete_Order_Quantity { get; set; }
        public decimal Minimum_Order_Quantity { get; set; }
        public decimal Maximum_Order_Quantity { get; set; }
        public decimal Safety_Stock_Quantity { get; set; }
        public decimal Order_Multiple { get; set; }
        public string Safety_Lead_Time { get; set; }
        public int Flushing_Method { get; set; }
        public int Replenishment_System { get; set; }
        public decimal Rounding_Precision { get; set; }
        public string Sales_Unit_of_Measure { get; set; }
        public string Purch__Unit_of_Measure { get; set; }
        public string Time_Bucket { get; set; }
        public int Reordering_Policy { get; set; }
        public byte Include_Inventory { get; set; }
        public int Manufacturing_Policy { get; set; }
        public string Rescheduling_Period { get; set; }
        public string Lot_Accumulation_Period { get; set; }
        public string Dampener_Period { get; set; }
        public decimal Dampener_Quantity { get; set; }
        public decimal Overflow_Level { get; set; }
        public string Manufacturer_Code { get; set; }
        public string Item_Category_Code { get; set; }
        public byte Created_From_Nonstock_Item { get; set; }
        public string Product_Group_Code { get; set; }
        public string Service_Item_Group { get; set; }
        public string Item_Tracking_Code { get; set; }
        public string Lot_Nos_ { get; set; }
        public string Expiration_Calculation { get; set; }
        public string Special_Equipment_Code { get; set; }
        public string Put_away_Template_Code { get; set; }
        public string Put_away_Unit_of_Measure_Code { get; set; }
        public string Phys_Invt_Counting_Period_Code { get; set; }
        public System.DateTime Last_Counting_Period_Update { get; set; }
        public string Next_Counting_Period { get; set; }
        public byte Use_Cross_Docking { get; set; }
        public string Load_Cell_Family { get; set; }
        public string Load_Cell_Capacity { get; set; }
        public string Load_Cell_Type { get; set; }
        public byte Koggala_Item { get; set; }
        public byte Local_Purchase { get; set; }
        public string Drawing_No_ { get; set; }
        public byte Major_Prod__Component { get; set; }
        public string Old_FG_Part_No_ { get; set; }
        public string Item_Cross_Reference { get; set; }
        public string Instruction_File_No_ { get; set; }
        public decimal Yield_Varience____ { get; set; }
        public string Components_at_Location { get; set; }
        public byte KG_Item_Received_at_KT { get; set; }
        public byte Inv__In_Both_Loc { get; set; }
        public string Bar_Code { get; set; }
        public string Application_Type { get; set; }
        public string Market_Sector { get; set; }
        public string Routing_No_ { get; set; }
        public string Production_BOM_No_ { get; set; }
        public decimal Single_Level_Material_Cost { get; set; }
        public decimal Single_Level_Capacity_Cost { get; set; }
        public decimal Single_Level_Subcontrd__Cost { get; set; }
        public decimal Single_Level_Cap__Ovhd_Cost { get; set; }
        public decimal Single_Level_Mfg__Ovhd_Cost { get; set; }
        public decimal Overhead_Rate { get; set; }
        public decimal Rolled_up_Subcontracted_Cost { get; set; }
        public decimal Rolled_up_Mfg__Ovhd_Cost { get; set; }
        public decimal Rolled_up_Cap__Overhead_Cost { get; set; }
        public int Order_Tracking_Policy { get; set; }
        public byte Critical { get; set; }
        public string Common_Item_No_ { get; set; }
        public byte Subcontracted { get; set; }
        public string Manufacturing_Project { get; set; }
        public int Accessory_Category { get; set; }
    }
}
