//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRAINTEC_FA_Posting_Group_Buffer
    {
        public byte[] timestamp { get; set; }
        public string FA_Posting_Group { get; set; }
        public int Posting_Type { get; set; }
        public string Account_No_ { get; set; }
        public decimal Amount { get; set; }
        public string Account_Name { get; set; }
        public string FA_FieldCaption { get; set; }
    }
}
