//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRAINTEC_Inventory_Period_Entry
    {
        public byte[] timestamp { get; set; }
        public System.DateTime Ending_Date { get; set; }
        public int Entry_No_ { get; set; }
        public string User_ID { get; set; }
        public System.DateTime Creation_Date { get; set; }
        public System.DateTime Creation_Time { get; set; }
        public int Closing_Item_Register_No_ { get; set; }
        public int Entry_Type { get; set; }
        public string Description { get; set; }
    }
}
