//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRAINTEC_Service_E_Mail_Queue
    {
        public byte[] timestamp { get; set; }
        public int Entry_No_ { get; set; }
        public string To_Address { get; set; }
        public string Copy_to_Address { get; set; }
        public string Subject_Line { get; set; }
        public string Body_Line { get; set; }
        public string Attachment_Filename { get; set; }
        public System.DateTime Sending_Date { get; set; }
        public System.DateTime Sending_Time { get; set; }
        public int Status { get; set; }
        public int Document_Type { get; set; }
        public string Document_No_ { get; set; }
    }
}
