//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRAINTEC_Dimensions_Field_Map
    {
        public byte[] timestamp { get; set; }
        public int Table_No_ { get; set; }
        public int Global_Dim_1_Field_No_ { get; set; }
        public int Global_Dim_2_Field_No_ { get; set; }
        public int ID_Field_No_ { get; set; }
    }
}
