//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRAINTEC_Standard_Cost_Breakdown_Header
    {
        public byte[] timestamp { get; set; }
        public string No_ { get; set; }
        public System.DateTime Last_Unit_Cost_Calc__Date { get; set; }
        public int Version { get; set; }
        public decimal Rollup_Cost { get; set; }
        public decimal Overhead_Cost { get; set; }
        public decimal Standard_Cost { get; set; }
    }
}
