//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRAINTEC_Reminder_Header
    {
        public byte[] timestamp { get; set; }
        public string No_ { get; set; }
        public string Customer_No_ { get; set; }
        public string Name { get; set; }
        public string Name_2 { get; set; }
        public string Address { get; set; }
        public string Address_2 { get; set; }
        public string Post_Code { get; set; }
        public string City { get; set; }
        public string County { get; set; }
        public string Country_Region_Code { get; set; }
        public string Language_Code { get; set; }
        public string Currency_Code { get; set; }
        public string Contact { get; set; }
        public string Your_Reference { get; set; }
        public string Shortcut_Dimension_1_Code { get; set; }
        public string Shortcut_Dimension_2_Code { get; set; }
        public string Customer_Posting_Group { get; set; }
        public string Gen__Bus__Posting_Group { get; set; }
        public string VAT_Registration_No_ { get; set; }
        public string Reason_Code { get; set; }
        public System.DateTime Posting_Date { get; set; }
        public System.DateTime Document_Date { get; set; }
        public System.DateTime Due_Date { get; set; }
        public string Reminder_Terms_Code { get; set; }
        public string Fin__Charge_Terms_Code { get; set; }
        public byte Post_Interest { get; set; }
        public byte Post_Additional_Fee { get; set; }
        public int Reminder_Level { get; set; }
        public string Posting_Description { get; set; }
        public string No__Series { get; set; }
        public string Issuing_No__Series { get; set; }
        public string Issuing_No_ { get; set; }
        public string Tax_Area_Code { get; set; }
        public byte Tax_Liable { get; set; }
        public string VAT_Bus__Posting_Group { get; set; }
        public byte Use_Header_Level { get; set; }
        public int Dimension_Set_ID { get; set; }
        public string Assigned_User_ID { get; set; }
    }
}
