//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRAINTEC_Job_Queue_Log_Entry
    {
        public byte[] timestamp { get; set; }
        public int Entry_No_ { get; set; }
        public System.Guid ID { get; set; }
        public string User_ID { get; set; }
        public System.DateTime Start_Date_Time { get; set; }
        public System.DateTime End_Date_Time { get; set; }
        public int Object_Type_to_Run { get; set; }
        public int Object_ID_to_Run { get; set; }
        public int Status { get; set; }
        public string Description { get; set; }
        public string Error_Message { get; set; }
        public string Error_Message_2 { get; set; }
        public string Error_Message_3 { get; set; }
        public string Error_Message_4 { get; set; }
        public string Job_Queue_Code { get; set; }
        public string Processed_by_User_ID { get; set; }
        public string Job_Queue_Category_Code { get; set; }
    }
}
