//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRAINTEC_Sales___Receivables_Setup
    {
        public byte[] timestamp { get; set; }
        public string Primary_Key { get; set; }
        public int Discount_Posting { get; set; }
        public int Credit_Warnings { get; set; }
        public byte Stockout_Warning { get; set; }
        public byte Shipment_on_Invoice { get; set; }
        public byte Invoice_Rounding { get; set; }
        public byte Ext__Doc__No__Mandatory { get; set; }
        public string Customer_Nos_ { get; set; }
        public string Quote_Nos_ { get; set; }
        public string Order_Nos_ { get; set; }
        public string Invoice_Nos_ { get; set; }
        public string Posted_Invoice_Nos_ { get; set; }
        public string Credit_Memo_Nos_ { get; set; }
        public string Posted_Credit_Memo_Nos_ { get; set; }
        public string Posted_Shipment_Nos_ { get; set; }
        public string Reminder_Nos_ { get; set; }
        public string Issued_Reminder_Nos_ { get; set; }
        public string Fin__Chrg__Memo_Nos_ { get; set; }
        public string Issued_Fin__Chrg__M__Nos_ { get; set; }
        public string Posted_Prepmt__Inv__Nos_ { get; set; }
        public string Posted_Prepmt__Cr__Memo_Nos_ { get; set; }
        public string Blanket_Order_Nos_ { get; set; }
        public byte Calc__Inv__Discount { get; set; }
        public int Appln__between_Currencies { get; set; }
        public byte Copy_Comments_Blanket_to_Order { get; set; }
        public byte Copy_Comments_Order_to_Invoice { get; set; }
        public byte Copy_Comments_Order_to_Shpt_ { get; set; }
        public byte Allow_VAT_Difference { get; set; }
        public byte Calc__Inv__Disc__per_VAT_ID { get; set; }
        public int Logo_Position_on_Documents { get; set; }
        public byte Check_Prepmt__when_Posting { get; set; }
        public int Default_Posting_Date { get; set; }
        public int Default_Quantity_to_Ship { get; set; }
        public byte Archive_Quotes_and_Orders { get; set; }
        public byte Post_with_Job_Queue { get; set; }
        public string Job_Queue_Category_Code { get; set; }
        public int Job_Queue_Priority_for_Post { get; set; }
        public byte Post___Print_with_Job_Queue { get; set; }
        public int Job_Q__Prio__for_Post___Print { get; set; }
        public byte Notify_On_Success { get; set; }
        public string VAT_Bus__Posting_Gr___Price_ { get; set; }
        public string Direct_Debit_Mandate_Nos_ { get; set; }
        public string Posted_Return_Receipt_Nos_ { get; set; }
        public byte Copy_Cmts_Ret_Ord__to_Ret_Rcpt { get; set; }
        public byte Copy_Cmts_Ret_Ord__to_Cr__Memo { get; set; }
        public string Return_Order_Nos_ { get; set; }
        public byte Return_Receipt_on_Credit_Memo { get; set; }
        public byte Exact_Cost_Reversing_Mandatory { get; set; }
        public string Customer_Group_Dimension_Code { get; set; }
        public string Salesperson_Dimension_Code { get; set; }
        public byte Upload_Sales_Budget { get; set; }
        public string RMA_Nos_ { get; set; }
        public string Packing_List_Nos_ { get; set; }
    }
}
