//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRAINTEC_Cost_Type
    {
        public byte[] timestamp { get; set; }
        public string No_ { get; set; }
        public string Name { get; set; }
        public string Search_Name { get; set; }
        public int Type { get; set; }
        public string Cost_Center_Code { get; set; }
        public string Cost_Object_Code { get; set; }
        public int Combine_Entries { get; set; }
        public byte Blocked { get; set; }
        public byte New_Page { get; set; }
        public byte Blank_Line { get; set; }
        public int Indentation { get; set; }
        public string Comment { get; set; }
        public int Cost_Classification { get; set; }
        public string Fixed_Share { get; set; }
        public System.DateTime Modified_Date { get; set; }
        public string Modified_By { get; set; }
        public string Totaling { get; set; }
        public decimal Budget_at_Date { get; set; }
        public string G_L_Account_Range { get; set; }
    }
}
