//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRAINTEC_Rating
    {
        public byte[] timestamp { get; set; }
        public string Profile_Questionnaire_Code { get; set; }
        public int Profile_Questionnaire_Line_No_ { get; set; }
        public string Rating_Profile_Quest__Code { get; set; }
        public int Rating_Profile_Quest__Line_No_ { get; set; }
        public decimal Points { get; set; }
    }
}
