//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRAINTEC_Cont__Duplicate_Search_String
    {
        public byte[] timestamp { get; set; }
        public string Contact_Company_No_ { get; set; }
        public int Field { get; set; }
        public int Part_of_Field { get; set; }
        public string Search_String { get; set; }
    }
}
