//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRAINTEC_Item_Charge
    {
        public byte[] timestamp { get; set; }
        public string No_ { get; set; }
        public string Description { get; set; }
        public string Gen__Prod__Posting_Group { get; set; }
        public string Tax_Group_Code { get; set; }
        public string VAT_Prod__Posting_Group { get; set; }
        public string Search_Description { get; set; }
        public string Global_Dimension_1_Code { get; set; }
        public string Global_Dimension_2_Code { get; set; }
    }
}
