//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRAINTEC_Item_Charge_Assignment__Sales_
    {
        public byte[] timestamp { get; set; }
        public int Document_Type { get; set; }
        public string Document_No_ { get; set; }
        public int Document_Line_No_ { get; set; }
        public int Line_No_ { get; set; }
        public string Item_Charge_No_ { get; set; }
        public string Item_No_ { get; set; }
        public string Description { get; set; }
        public decimal Qty__to_Assign { get; set; }
        public decimal Qty__Assigned { get; set; }
        public decimal Unit_Cost { get; set; }
        public decimal Amount_to_Assign { get; set; }
        public int Applies_to_Doc__Type { get; set; }
        public string Applies_to_Doc__No_ { get; set; }
        public int Applies_to_Doc__Line_No_ { get; set; }
        public decimal Applies_to_Doc__Line_Amount { get; set; }
    }
}
