//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRAINTEC_XBRL_G_L_Map_Line
    {
        public byte[] timestamp { get; set; }
        public string XBRL_Taxonomy_Name { get; set; }
        public int XBRL_Taxonomy_Line_No_ { get; set; }
        public int Line_No_ { get; set; }
        public string G_L_Account_Filter { get; set; }
        public string Business_Unit_Filter { get; set; }
        public string Global_Dimension_1_Filter { get; set; }
        public string Global_Dimension_2_Filter { get; set; }
        public int Timeframe_Type { get; set; }
        public int Amount_Type { get; set; }
        public int Normal_Balance { get; set; }
    }
}
