//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRAINTEC_Contract_Gain_Loss_Entry
    {
        public byte[] timestamp { get; set; }
        public int Entry_No_ { get; set; }
        public string Contract_No_ { get; set; }
        public string Contract_Group_Code { get; set; }
        public System.DateTime Change_Date { get; set; }
        public string Reason_Code { get; set; }
        public int Type_of_Change { get; set; }
        public string Responsibility_Center { get; set; }
        public string Customer_No_ { get; set; }
        public string Ship_to_Code { get; set; }
        public string User_ID { get; set; }
        public decimal Amount { get; set; }
    }
}
