//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRAINTEC_Misc__Article_Information
    {
        public byte[] timestamp { get; set; }
        public string Employee_No_ { get; set; }
        public string Misc__Article_Code { get; set; }
        public int Line_No_ { get; set; }
        public string Description { get; set; }
        public System.DateTime From_Date { get; set; }
        public System.DateTime To_Date { get; set; }
        public byte In_Use { get; set; }
        public string Serial_No_ { get; set; }
    }
}
