//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRAINTEC_Dimension_Code_Buffer
    {
        public byte[] timestamp { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Totaling { get; set; }
        public System.DateTime Period_Start { get; set; }
        public System.DateTime Period_End { get; set; }
        public byte Visible { get; set; }
        public int Indentation { get; set; }
        public byte Show_in_Bold { get; set; }
    }
}
