//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRAINTEC_Invoice_Post__Buffer
    {
        public byte[] timestamp { get; set; }
        public int Type { get; set; }
        public string G_L_Account { get; set; }
        public string Gen__Bus__Posting_Group { get; set; }
        public string Gen__Prod__Posting_Group { get; set; }
        public string VAT_Bus__Posting_Group { get; set; }
        public string VAT_Prod__Posting_Group { get; set; }
        public string Tax_Area_Code { get; set; }
        public string Tax_Group_Code { get; set; }
        public byte Tax_Liable { get; set; }
        public byte Use_Tax { get; set; }
        public int Dimension_Set_ID { get; set; }
        public string Job_No_ { get; set; }
        public int Fixed_Asset_Line_No_ { get; set; }
        public string Global_Dimension_1_Code { get; set; }
        public string Global_Dimension_2_Code { get; set; }
        public decimal Amount { get; set; }
        public decimal VAT_Amount { get; set; }
        public int VAT_Calculation_Type { get; set; }
        public decimal VAT_Base_Amount { get; set; }
        public byte System_Created_Entry { get; set; }
        public decimal Quantity { get; set; }
        public decimal Amount__ACY_ { get; set; }
        public decimal VAT_Amount__ACY_ { get; set; }
        public decimal VAT_Base_Amount__ACY_ { get; set; }
        public decimal VAT_Difference { get; set; }
        public decimal VAT__ { get; set; }
        public System.DateTime FA_Posting_Date { get; set; }
        public int FA_Posting_Type { get; set; }
        public string Depreciation_Book_Code { get; set; }
        public decimal Salvage_Value { get; set; }
        public byte Depr__until_FA_Posting_Date { get; set; }
        public byte Depr__Acquisition_Cost { get; set; }
        public string Maintenance_Code { get; set; }
        public string Insurance_No_ { get; set; }
        public string Budgeted_FA_No_ { get; set; }
        public string Duplicate_in_Depreciation_Book { get; set; }
        public byte Use_Duplication_List { get; set; }
        public string GL_Description { get; set; }
    }
}
