//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRAINTEC_Analysis_View_Budget_Entry
    {
        public byte[] timestamp { get; set; }
        public string Analysis_View_Code { get; set; }
        public string Budget_Name { get; set; }
        public string G_L_Account_No_ { get; set; }
        public string Dimension_1_Value_Code { get; set; }
        public string Dimension_2_Value_Code { get; set; }
        public string Dimension_3_Value_Code { get; set; }
        public string Dimension_4_Value_Code { get; set; }
        public string Business_Unit_Code { get; set; }
        public System.DateTime Posting_Date { get; set; }
        public int Entry_No_ { get; set; }
        public decimal Amount { get; set; }
    }
}
