//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRAINTEC_Planning_Component
    {
        public byte[] timestamp { get; set; }
        public string Worksheet_Template_Name { get; set; }
        public string Worksheet_Batch_Name { get; set; }
        public int Worksheet_Line_No_ { get; set; }
        public int Line_No_ { get; set; }
        public string Item_No_ { get; set; }
        public string Description { get; set; }
        public string Unit_of_Measure_Code { get; set; }
        public decimal Quantity { get; set; }
        public string Position { get; set; }
        public string Position_2 { get; set; }
        public string Position_3 { get; set; }
        public string Lead_Time_Offset { get; set; }
        public string Routing_Link_Code { get; set; }
        public decimal Scrap__ { get; set; }
        public string Variant_Code { get; set; }
        public decimal Expected_Quantity { get; set; }
        public int Flushing_Method { get; set; }
        public string Location_Code { get; set; }
        public string Shortcut_Dimension_1_Code { get; set; }
        public string Shortcut_Dimension_2_Code { get; set; }
        public string Bin_Code { get; set; }
        public int Supplied_by_Line_No_ { get; set; }
        public int Planning_Level_Code { get; set; }
        public int Ref__Order_Status { get; set; }
        public string Ref__Order_No_ { get; set; }
        public int Ref__Order_Line_No_ { get; set; }
        public decimal Length { get; set; }
        public decimal Width { get; set; }
        public decimal Weight { get; set; }
        public decimal Depth { get; set; }
        public int Calculation_Formula { get; set; }
        public decimal Quantity_per { get; set; }
        public int Ref__Order_Type { get; set; }
        public decimal Unit_Cost { get; set; }
        public decimal Cost_Amount { get; set; }
        public System.DateTime Due_Date { get; set; }
        public System.DateTime Due_Time { get; set; }
        public decimal Direct_Unit_Cost { get; set; }
        public decimal Indirect_Cost__ { get; set; }
        public decimal Overhead_Rate { get; set; }
        public decimal Direct_Cost_Amount { get; set; }
        public decimal Overhead_Amount { get; set; }
        public decimal Qty__per_Unit_of_Measure { get; set; }
        public decimal Quantity__Base_ { get; set; }
        public decimal Expected_Quantity__Base_ { get; set; }
        public decimal Original_Expected_Qty___Base_ { get; set; }
        public decimal Net_Quantity__Base_ { get; set; }
        public System.DateTime Due_Date_Time { get; set; }
        public int Dimension_Set_ID { get; set; }
        public byte Critical { get; set; }
        public int Planning_Line_Origin { get; set; }
    }
}
