//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRAINTEC_Journal_Approvals
    {
        public byte[] timestamp { get; set; }
        public string Approver_User_ID { get; set; }
        public string Gen__Journal_Template_Name { get; set; }
        public string Batch_Name { get; set; }
        public string Create_User_ID { get; set; }
    }
}
