//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRAINTEC_Cash_Flow_Setup
    {
        public byte[] timestamp { get; set; }
        public string Primary_Key { get; set; }
        public string Cash_Flow_Forecast_No__Series { get; set; }
        public string Receivables_CF_Account_No_ { get; set; }
        public string Payables_CF_Account_No_ { get; set; }
        public string Sales_Order_CF_Account_No_ { get; set; }
        public string Purch__Order_CF_Account_No_ { get; set; }
        public string FA_Budget_CF_Account_No_ { get; set; }
        public string FA_Disposal_CF_Account_No_ { get; set; }
        public string Service_CF_Account_No_ { get; set; }
        public string CF_No__on_Chart_in_Role_Center { get; set; }
    }
}
