//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRAINTEC_Posting_Exch__Def
    {
        public byte[] timestamp { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public int Type { get; set; }
        public int Processing_XMLport { get; set; }
        public int Header_Lines { get; set; }
        public string Header_Tag { get; set; }
        public string Footer_Tag { get; set; }
        public int Column_Separator { get; set; }
        public int File_Encoding { get; set; }
        public int File_Type { get; set; }
        public int Importing_Codeunit { get; set; }
        public int Processing_Codeunit { get; set; }
    }
}
