//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRAINTEC_Dimension_Selection_Buffer
    {
        public byte[] timestamp { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public byte Selected { get; set; }
        public string New_Dimension_Value_Code { get; set; }
        public string Dimension_Value_Filter { get; set; }
        public int Level { get; set; }
        public int Filter_Lookup_Table_No_ { get; set; }
    }
}
