//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRAINTEC_Cash_Flow_Worksheet_Line
    {
        public byte[] timestamp { get; set; }
        public int Line_No_ { get; set; }
        public string Cash_Flow_Forecast_No_ { get; set; }
        public System.DateTime Cash_Flow_Date { get; set; }
        public string Document_No_ { get; set; }
        public string Cash_Flow_Account_No_ { get; set; }
        public int Source_Type { get; set; }
        public string Description { get; set; }
        public int Document_Type { get; set; }
        public System.DateTime Document_Date { get; set; }
        public System.DateTime Pmt__Discount_Date { get; set; }
        public System.DateTime Pmt__Disc__Tolerance_Date { get; set; }
        public string Payment_Terms_Code { get; set; }
        public decimal Payment_Discount { get; set; }
        public int Associated_Entry_No_ { get; set; }
        public string Shortcut_Dimension_2_Code { get; set; }
        public string Shortcut_Dimension_1_Code { get; set; }
        public decimal Amount__LCY_ { get; set; }
        public string Source_No_ { get; set; }
        public string G_L_Budget_Name { get; set; }
        public int Dimension_Set_ID { get; set; }
    }
}
