//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRAINTEC_Zone
    {
        public byte[] timestamp { get; set; }
        public string Location_Code { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public string Bin_Type_Code { get; set; }
        public string Warehouse_Class_Code { get; set; }
        public string Special_Equipment_Code { get; set; }
        public int Zone_Ranking { get; set; }
        public byte Cross_Dock_Bin_Zone { get; set; }
    }
}
