//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRAINTEC_Sales_Prepayment__
    {
        public byte[] timestamp { get; set; }
        public string Item_No_ { get; set; }
        public int Sales_Type { get; set; }
        public string Sales_Code { get; set; }
        public System.DateTime Starting_Date { get; set; }
        public System.DateTime Ending_Date { get; set; }
        public decimal Prepayment__ { get; set; }
    }
}
