//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRAINTEC_Item_Translation
    {
        public byte[] timestamp { get; set; }
        public string Item_No_ { get; set; }
        public string Variant_Code { get; set; }
        public string Language_Code { get; set; }
        public string Description { get; set; }
        public string Description_2 { get; set; }
    }
}
