//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRAINTEC_Logged_Segment
    {
        public byte[] timestamp { get; set; }
        public int Entry_No_ { get; set; }
        public string Segment_No_ { get; set; }
        public string Description { get; set; }
        public System.DateTime Creation_Date { get; set; }
        public string User_ID { get; set; }
        public byte Canceled { get; set; }
    }
}
