//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRAINTEC_Purchase_Requisition_Line
    {
        public byte[] timestamp { get; set; }
        public string Purch_Rec__No_ { get; set; }
        public int Line_No_ { get; set; }
        public string No_ { get; set; }
        public string Description { get; set; }
        public decimal Quantity { get; set; }
        public string Location { get; set; }
        public string Vendor { get; set; }
        public byte Released { get; set; }
        public byte Create_PO { get; set; }
        public string Unit_of_Measure { get; set; }
        public string Requester_ID { get; set; }
        public System.DateTime Created_Date { get; set; }
        public int Type { get; set; }
        public byte Select_to_create_PO { get; set; }
        public string PO_Ref__No_ { get; set; }
        public string Created_By { get; set; }
        public string Responsible_User_to_Create_PO { get; set; }
        public string Machine { get; set; }
        public string Machine_Serial_No_ { get; set; }
        public string User_Department { get; set; }
        public int Part_Required_For { get; set; }
        public decimal Unit_Price { get; set; }
        public System.DateTime Required_Date { get; set; }
        public string Responsibility_Center { get; set; }
        public System.DateTime Assigned_Date { get; set; }
        public decimal Unit_Total { get; set; }
    }
}
