//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRAINTEC_Outlook_Synch__Setup_Detail
    {
        public byte[] timestamp { get; set; }
        public string User_ID { get; set; }
        public string Synch__Entity_Code { get; set; }
        public int Element_No_ { get; set; }
        public int Table_No_ { get; set; }
    }
}
