//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRAINTEC_Post_Value_Entry_to_G_L
    {
        public byte[] timestamp { get; set; }
        public int Value_Entry_No_ { get; set; }
        public string Item_No_ { get; set; }
        public System.DateTime Posting_Date { get; set; }
    }
}
