//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRAINTEC_Mini_Vendor_Template
    {
        public byte[] timestamp { get; set; }
        public int Key { get; set; }
        public string Code { get; set; }
        public string Template_Name { get; set; }
        public string City { get; set; }
        public string Vendor_Posting_Group { get; set; }
        public string Currency_Code { get; set; }
        public string Language_Code { get; set; }
        public string Payment_Terms_Code { get; set; }
        public string Fin__Charge_Terms_Code { get; set; }
        public string Invoice_Disc__Code { get; set; }
        public string Country_Region_Code { get; set; }
        public string Payment_Method_Code { get; set; }
        public int Application_Method { get; set; }
        public byte Prices_Including_VAT { get; set; }
        public string Gen__Bus__Posting_Group { get; set; }
        public string Post_Code { get; set; }
        public string County { get; set; }
        public string VAT_Bus__Posting_Group { get; set; }
        public byte Block_Payment_Tolerance { get; set; }
    }
}
