//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRAINTEC_Bin_Content_Buffer
    {
        public byte[] timestamp { get; set; }
        public string Location_Code { get; set; }
        public string Bin_Code { get; set; }
        public string Item_No_ { get; set; }
        public string Variant_Code { get; set; }
        public string Unit_of_Measure_Code { get; set; }
        public string Lot_No_ { get; set; }
        public string Serial_No_ { get; set; }
        public string Zone_Code { get; set; }
        public decimal Cubage { get; set; }
        public decimal Weight { get; set; }
        public string Base_Unit_of_Measure { get; set; }
        public decimal Qty__to_Handle__Base_ { get; set; }
        public decimal Qty__Outstanding__Base_ { get; set; }
    }
}
