//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRAINTEC_Cost_Accounting_Setup
    {
        public byte[] timestamp { get; set; }
        public string Primary_Key { get; set; }
        public System.DateTime Starting_Date_for_G_L_Transfer { get; set; }
        public int Align_G_L_Account { get; set; }
        public int Align_Cost_Center_Dimension { get; set; }
        public int Align_Cost_Object_Dimension { get; set; }
        public string Last_Allocation_ID { get; set; }
        public string Last_Allocation_Doc__No_ { get; set; }
        public byte Auto_Transfer_from_G_L { get; set; }
        public byte Check_G_L_Postings { get; set; }
        public string Cost_Center_Dimension { get; set; }
        public string Cost_Object_Dimension { get; set; }
    }
}
