//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRAINTEC_Inventory_Report_Header
    {
        public byte[] timestamp { get; set; }
        public string Code { get; set; }
        public byte Calculated { get; set; }
        public int Line_Option { get; set; }
        public int Column_Option { get; set; }
        public byte Show_Warning { get; set; }
    }
}
