//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRAINTEC_To_do_Interaction_Language
    {
        public byte[] timestamp { get; set; }
        public string To_do_No_ { get; set; }
        public string Language_Code { get; set; }
        public string Description { get; set; }
        public int Attachment_No_ { get; set; }
    }
}
