//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRAINTEC_FA_Matrix_Posting_Type
    {
        public byte[] timestamp { get; set; }
        public int Entry_No_ { get; set; }
        public string FA_Posting_Type_Name { get; set; }
    }
}
