//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRAINTEC_Purchase_Requisition_Header
    {
        public byte[] timestamp { get; set; }
        public string Purch_Rec__No_ { get; set; }
        public int Status { get; set; }
        public string Requester_ID { get; set; }
        public System.DateTime Created_Date { get; set; }
        public string Created_By { get; set; }
        public string Initial_Approver { get; set; }
        public int Initial_Approval_Status { get; set; }
        public System.DateTime Initial_Approval_Date { get; set; }
        public string User_Department { get; set; }
        public string Responsibility_Center { get; set; }
        public System.DateTime Released_Date { get; set; }
    }
}
