//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRAINTEC_Config__Package_Table
    {
        public byte[] timestamp { get; set; }
        public string Package_Code { get; set; }
        public int Table_ID { get; set; }
        public System.DateTime Imported_Date_and_Time { get; set; }
        public System.DateTime Exported_Date_and_Time { get; set; }
        public string Comments { get; set; }
        public System.DateTime Created_Date_and_Time { get; set; }
        public string Data_Template { get; set; }
        public int Package_Processing_Order { get; set; }
        public int Page_ID { get; set; }
        public int Processing_Order { get; set; }
        public string Imported_by_User_ID { get; set; }
        public string Created_by_User_ID { get; set; }
        public byte Dimensions_as_Columns { get; set; }
        public byte Skip_Table_Triggers { get; set; }
    }
}
