//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRAINTEC_FA_Posting_Type_Setup
    {
        public byte[] timestamp { get; set; }
        public string Depreciation_Book_Code { get; set; }
        public int FA_Posting_Type { get; set; }
        public byte Part_of_Book_Value { get; set; }
        public byte Part_of_Depreciable_Basis { get; set; }
        public byte Include_in_Depr__Calculation { get; set; }
        public byte Include_in_Gain_Loss_Calc_ { get; set; }
        public byte Reverse_before_Disposal { get; set; }
        public int Sign { get; set; }
        public byte Depreciation_Type { get; set; }
        public byte Acquisition_Type { get; set; }
    }
}
