//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRAINTEC_Accounting_Period
    {
        public byte[] timestamp { get; set; }
        public System.DateTime Starting_Date { get; set; }
        public string Name { get; set; }
        public byte New_Fiscal_Year { get; set; }
        public byte Closed { get; set; }
        public byte Date_Locked { get; set; }
        public int Average_Cost_Calc__Type { get; set; }
        public int Average_Cost_Period { get; set; }
    }
}
