//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRAINTEC_Warehouse_Journal_Line
    {
        public byte[] timestamp { get; set; }
        public string Journal_Template_Name { get; set; }
        public string Journal_Batch_Name { get; set; }
        public string Location_Code { get; set; }
        public int Line_No_ { get; set; }
        public System.DateTime Registering_Date { get; set; }
        public string From_Zone_Code { get; set; }
        public string From_Bin_Code { get; set; }
        public string Description { get; set; }
        public string Item_No_ { get; set; }
        public decimal Quantity { get; set; }
        public decimal Qty___Base_ { get; set; }
        public decimal Qty___Absolute_ { get; set; }
        public decimal Qty___Absolute__Base_ { get; set; }
        public string Zone_Code { get; set; }
        public string Bin_Code { get; set; }
        public int Source_Type { get; set; }
        public int Source_Subtype { get; set; }
        public string Source_No_ { get; set; }
        public int Source_Line_No_ { get; set; }
        public int Source_Subline_No_ { get; set; }
        public int Source_Document { get; set; }
        public string Source_Code { get; set; }
        public string To_Zone_Code { get; set; }
        public string To_Bin_Code { get; set; }
        public string Reason_Code { get; set; }
        public string Registering_No__Series { get; set; }
        public string From_Bin_Type_Code { get; set; }
        public decimal Cubage { get; set; }
        public decimal Weight { get; set; }
        public string Whse__Document_No_ { get; set; }
        public int Whse__Document_Type { get; set; }
        public int Whse__Document_Line_No_ { get; set; }
        public decimal Qty___Calculated_ { get; set; }
        public decimal Qty___Phys__Inventory_ { get; set; }
        public int Entry_Type { get; set; }
        public byte Phys__Inventory { get; set; }
        public int Reference_Document { get; set; }
        public string Reference_No_ { get; set; }
        public string User_ID { get; set; }
        public decimal Qty___Calculated___Base_ { get; set; }
        public decimal Qty___Phys__Inventory___Base_ { get; set; }
        public string Variant_Code { get; set; }
        public decimal Qty__per_Unit_of_Measure { get; set; }
        public string Unit_of_Measure_Code { get; set; }
        public string Serial_No_ { get; set; }
        public string Lot_No_ { get; set; }
        public System.DateTime Warranty_Date { get; set; }
        public System.DateTime Expiration_Date { get; set; }
        public string New_Serial_No_ { get; set; }
        public string New_Lot_No_ { get; set; }
        public System.DateTime New_Expiration_Date { get; set; }
        public string Phys_Invt_Counting_Period_Code { get; set; }
        public int Phys_Invt_Counting_Period_Type { get; set; }
    }
}
