//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRAINTEC_Config__Line
    {
        public byte[] timestamp { get; set; }
        public int Line_No_ { get; set; }
        public int Line_Type { get; set; }
        public int Table_ID { get; set; }
        public string Name { get; set; }
        public byte Promoted_Table { get; set; }
        public byte Dimensions_as_Columns { get; set; }
        public byte Copying_Available { get; set; }
        public int Page_ID { get; set; }
        public System.DateTime Starting_Date { get; set; }
        public System.DateTime Ending_Date { get; set; }
        public string Responsible_ID { get; set; }
        public int Status { get; set; }
        public int Vertical_Sorting { get; set; }
        public string Data_Origin { get; set; }
        public string Reference { get; set; }
        public int Parent_Line_No_ { get; set; }
        public string Package_Code { get; set; }
    }
}
