//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRAINTEC_Config__Question
    {
        public byte[] timestamp { get; set; }
        public string Questionnaire_Code { get; set; }
        public string Question_Area_Code { get; set; }
        public int No_ { get; set; }
        public string Question { get; set; }
        public string Answer_Option { get; set; }
        public string Answer { get; set; }
        public int Table_ID { get; set; }
        public int Field_ID { get; set; }
        public string Reference { get; set; }
        public string Question_Origin { get; set; }
    }
}
