//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRAINTEC_DO_Payment_Setup
    {
        public byte[] timestamp { get; set; }
        public string Primary_Key { get; set; }
        public byte Authorization_Required { get; set; }
        public int Days_Before_Authoriz__Expiry { get; set; }
        public string Credit_Card_Nos_ { get; set; }
        public int Charge_Type { get; set; }
        public decimal Charge_Value { get; set; }
        public decimal Max__Charge_Amount__LCY_ { get; set; }
    }
}
