//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRAINTEC_Requisition_Line
    {
        public byte[] timestamp { get; set; }
        public string Worksheet_Template_Name { get; set; }
        public string Journal_Batch_Name { get; set; }
        public int Line_No_ { get; set; }
        public int Type { get; set; }
        public string No_ { get; set; }
        public string Description { get; set; }
        public string Description_2 { get; set; }
        public decimal Quantity { get; set; }
        public string Vendor_No_ { get; set; }
        public decimal Direct_Unit_Cost { get; set; }
        public System.DateTime Due_Date { get; set; }
        public string Requester_ID { get; set; }
        public byte Confirmed { get; set; }
        public string Shortcut_Dimension_1_Code { get; set; }
        public string Shortcut_Dimension_2_Code { get; set; }
        public string Location_Code { get; set; }
        public int Recurring_Method { get; set; }
        public System.DateTime Expiration_Date { get; set; }
        public string Recurring_Frequency { get; set; }
        public System.DateTime Order_Date { get; set; }
        public string Vendor_Item_No_ { get; set; }
        public string Sales_Order_No_ { get; set; }
        public int Sales_Order_Line_No_ { get; set; }
        public string Sell_to_Customer_No_ { get; set; }
        public string Ship_to_Code { get; set; }
        public string Order_Address_Code { get; set; }
        public string Currency_Code { get; set; }
        public decimal Currency_Factor { get; set; }
        public int Dimension_Set_ID { get; set; }
        public string Prod__Order_No_ { get; set; }
        public string Variant_Code { get; set; }
        public string Bin_Code { get; set; }
        public decimal Qty__per_Unit_of_Measure { get; set; }
        public string Unit_of_Measure_Code { get; set; }
        public decimal Quantity__Base_ { get; set; }
        public int Demand_Type { get; set; }
        public int Demand_Subtype { get; set; }
        public string Demand_Order_No_ { get; set; }
        public int Demand_Line_No_ { get; set; }
        public int Demand_Ref__No_ { get; set; }
        public int Status { get; set; }
        public System.DateTime Demand_Date { get; set; }
        public decimal Demand_Quantity { get; set; }
        public decimal Demand_Quantity__Base_ { get; set; }
        public decimal Needed_Quantity { get; set; }
        public decimal Needed_Quantity__Base_ { get; set; }
        public byte Reserve { get; set; }
        public decimal Qty__per_UOM__Demand_ { get; set; }
        public string Unit_Of_Measure_Code__Demand_ { get; set; }
        public string Supply_From { get; set; }
        public string Original_Item_No_ { get; set; }
        public string Original_Variant_Code { get; set; }
        public int Level { get; set; }
        public decimal Demand_Qty__Available { get; set; }
        public string User_ID { get; set; }
        public string Item_Category_Code { get; set; }
        public byte Nonstock { get; set; }
        public string Purchasing_Code { get; set; }
        public string Product_Group_Code { get; set; }
        public string Transfer_from_Code { get; set; }
        public System.DateTime Transfer_Shipment_Date { get; set; }
        public decimal Line_Discount__ { get; set; }
        public string Routing_No_ { get; set; }
        public string Operation_No_ { get; set; }
        public string Work_Center_No_ { get; set; }
        public int Prod__Order_Line_No_ { get; set; }
        public byte MPS_Order { get; set; }
        public int Planning_Flexibility { get; set; }
        public int Routing_Reference_No_ { get; set; }
        public string Gen__Prod__Posting_Group { get; set; }
        public string Gen__Business_Posting_Group { get; set; }
        public int Low_Level_Code { get; set; }
        public string Production_BOM_Version_Code { get; set; }
        public string Routing_Version_Code { get; set; }
        public int Routing_Type { get; set; }
        public decimal Original_Quantity { get; set; }
        public decimal Finished_Quantity { get; set; }
        public decimal Remaining_Quantity { get; set; }
        public System.DateTime Original_Due_Date { get; set; }
        public decimal Scrap__ { get; set; }
        public System.DateTime Starting_Date { get; set; }
        public System.DateTime Starting_Time { get; set; }
        public System.DateTime Ending_Date { get; set; }
        public System.DateTime Ending_Time { get; set; }
        public string Production_BOM_No_ { get; set; }
        public decimal Indirect_Cost__ { get; set; }
        public decimal Overhead_Rate { get; set; }
        public decimal Unit_Cost { get; set; }
        public decimal Cost_Amount { get; set; }
        public int Replenishment_System { get; set; }
        public string Ref__Order_No_ { get; set; }
        public int Ref__Order_Type { get; set; }
        public int Ref__Order_Status { get; set; }
        public int Ref__Line_No_ { get; set; }
        public string No__Series { get; set; }
        public decimal Finished_Qty___Base_ { get; set; }
        public decimal Remaining_Qty___Base_ { get; set; }
        public int Related_to_Planning_Line { get; set; }
        public int Planning_Level { get; set; }
        public int Planning_Line_Origin { get; set; }
        public int Action_Message { get; set; }
        public byte Accept_Action_Message { get; set; }
        public decimal Net_Quantity__Base_ { get; set; }
        public System.DateTime Starting_Date_Time { get; set; }
        public System.DateTime Ending_Date_Time { get; set; }
        public string Order_Promising_ID { get; set; }
        public int Order_Promising_Line_No_ { get; set; }
        public int Order_Promising_Line_ID { get; set; }
    }
}
