//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRAINTEC_Posting_Exch__Mapping
    {
        public byte[] timestamp { get; set; }
        public string Posting_Exch__Def_Code { get; set; }
        public string Posting_Exch__Line_Def_Code { get; set; }
        public int Table_ID { get; set; }
        public string Name { get; set; }
        public int Mapping_Codeunit { get; set; }
        public int Posting_Exch__No__Field_ID { get; set; }
        public int Posting_Exch__Line_Field_ID { get; set; }
    }
}
