//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRAINTEC_IC_Comment_Line
    {
        public byte[] timestamp { get; set; }
        public int Table_Name { get; set; }
        public int Transaction_No_ { get; set; }
        public string IC_Partner_Code { get; set; }
        public int Transaction_Source { get; set; }
        public int Line_No_ { get; set; }
        public System.DateTime Date { get; set; }
        public string Comment { get; set; }
    }
}
