//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRAINTEC_Posting_Exch__Field
    {
        public byte[] timestamp { get; set; }
        public int Posting_Exch__No_ { get; set; }
        public int Line_No_ { get; set; }
        public int Column_No_ { get; set; }
        public string Node_Id { get; set; }
        public string Value { get; set; }
    }
}
