//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRAINTEC_No__Series_Line
    {
        public byte[] timestamp { get; set; }
        public string Series_Code { get; set; }
        public int Line_No_ { get; set; }
        public System.DateTime Starting_Date { get; set; }
        public string Starting_No_ { get; set; }
        public string Ending_No_ { get; set; }
        public string Warning_No_ { get; set; }
        public int Increment_by_No_ { get; set; }
        public string Last_No__Used { get; set; }
        public byte Open { get; set; }
        public System.DateTime Last_Date_Used { get; set; }
    }
}
