//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRAINTEC_Main_Asset_Component
    {
        public byte[] timestamp { get; set; }
        public string Main_Asset_No_ { get; set; }
        public string FA_No_ { get; set; }
        public string Description { get; set; }
    }
}
