//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRAINTEC_Item_Tracking_Comment
    {
        public byte[] timestamp { get; set; }
        public int Type { get; set; }
        public string Item_No_ { get; set; }
        public string Variant_Code { get; set; }
        public string Serial_Lot_No_ { get; set; }
        public int Line_No_ { get; set; }
        public System.DateTime Date { get; set; }
        public string Comment { get; set; }
    }
}
