//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRAINTEC_Substitution_Condition
    {
        public byte[] timestamp { get; set; }
        public int Type { get; set; }
        public string No_ { get; set; }
        public string Variant_Code { get; set; }
        public int Substitute_Type { get; set; }
        public string Substitute_No_ { get; set; }
        public string Substitute_Variant_Code { get; set; }
        public int Line_No_ { get; set; }
        public string Condition { get; set; }
    }
}
