//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRAINTEC_Posting_Exch__Field_Mapping
    {
        public byte[] timestamp { get; set; }
        public string Posting_Exch__Def_Code { get; set; }
        public string Posting_Exch__Line_Def_Code { get; set; }
        public int Table_ID { get; set; }
        public int Column_No_ { get; set; }
        public int Field_ID { get; set; }
        public byte Optional { get; set; }
        public byte Use_Default_Value { get; set; }
        public string Default_Value { get; set; }
        public decimal Multiplier { get; set; }
    }
}
