//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRAINTEC_Cost_Journal_Batch
    {
        public byte[] timestamp { get; set; }
        public string Journal_Template_Name { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Reason_Code { get; set; }
        public string Bal__Cost_Type_No_ { get; set; }
        public string Bal__Cost_Center_Code { get; set; }
        public string Bal__Cost_Object_Code { get; set; }
        public byte Delete_after_Posting { get; set; }
    }
}
