//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRAINTEC_Record_Buffer
    {
        public byte[] timestamp { get; set; }
        public int Entry_No_ { get; set; }
        public int Table_No_ { get; set; }
        public string Table_Name { get; set; }
        public byte[] Record_Identifier { get; set; }
        public string Search_Record_ID { get; set; }
        public string Primary_Key { get; set; }
        public int Primary_Key_Field_1_No_ { get; set; }
        public string Primary_Key_Field_1_Value { get; set; }
        public int Primary_Key_Field_2_No_ { get; set; }
        public string Primary_Key_Field_2_Value { get; set; }
        public int Primary_Key_Field_3_No_ { get; set; }
        public string Primary_Key_Field_3_Value { get; set; }
        public int Level { get; set; }
        public string Serial_No_ { get; set; }
        public string Lot_No_ { get; set; }
        public string Item_No_ { get; set; }
        public string Variant_Code { get; set; }
    }
}
