//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRAINTEC_Payment_Export_Data
    {
        public byte[] timestamp { get; set; }
        public int Entry_No_ { get; set; }
        public int Posting_Exch_Entry_No_ { get; set; }
        public int Line_No_ { get; set; }
        public string Posting_Exch__Line_Def_Code { get; set; }
        public string General_Journal_Template { get; set; }
        public string General_Journal_Batch_Name { get; set; }
        public int General_Journal_Line_No_ { get; set; }
        public string Sender_Bank_Account_Code { get; set; }
        public string Sender_Bank_Account_No_ { get; set; }
        public string Sender_Bank_BIC { get; set; }
        public string Recipient_Name { get; set; }
        public string Recipient_Address { get; set; }
        public string Recipient_City { get; set; }
        public string Recipient_Post_Code { get; set; }
        public string Recipient_Country_Region_Code { get; set; }
        public string Recipient_Reg__No_ { get; set; }
        public string Recipient_Acc__No_ { get; set; }
        public string Recipient_Bank_Acc__No_ { get; set; }
        public string Recipient_Bank_BIC { get; set; }
        public string Recipient_Bank_Name { get; set; }
        public string Recipient_Bank_Address { get; set; }
        public string Recipient_Bank_City { get; set; }
        public string Recipient_Bank_Country_Region { get; set; }
        public string Recipient_Creditor_No_ { get; set; }
        public string Recipient_Bank_Post_Code { get; set; }
        public string Message_Type { get; set; }
        public string Letter_to_Sender { get; set; }
        public string Recipient_Acknowledgement { get; set; }
        public string Short_Advice { get; set; }
        public string Message_to_Recipient_1 { get; set; }
        public string Message_to_Recipient_2 { get; set; }
        public decimal Amount { get; set; }
        public string Currency_Code { get; set; }
        public System.DateTime Transfer_Date { get; set; }
        public string Transfer_Type { get; set; }
        public string Document_No_ { get; set; }
        public string Recipient_Reference { get; set; }
        public string Payment_Reference { get; set; }
        public string SEPA_Payment_Information_ID { get; set; }
        public string SEPA_End_to_End_ID { get; set; }
        public string SEPA_Message_ID { get; set; }
        public int SEPA_Instruction_Priority { get; set; }
        public string SEPA_Instruction_Priority_Text { get; set; }
        public int SEPA_Payment_Method { get; set; }
        public string SEPA_Payment_Method_Text { get; set; }
        public byte SEPA_Batch_Booking { get; set; }
        public int SEPA_Charge_Bearer { get; set; }
        public string SEPA_Charge_Bearer_Text { get; set; }
        public string SEPA_Direct_Debit_Mandate_ID { get; set; }
        public int SEPA_Direct_Debit_Seq__Type { get; set; }
        public string SEPA_Direct_Debit_Seq__Text { get; set; }
        public System.DateTime SEPA_DD_Mandate_Signed_Date { get; set; }
        public int SEPA_Partner_Type { get; set; }
        public string SEPA_Partner_Type_Text { get; set; }
        public string Creditor_No_ { get; set; }
        public string Applies_to_Ext__Doc__No_ { get; set; }
        public string Format_Command { get; set; }
        public string Format_Remittance_Info_Type { get; set; }
        public string Format_Payment_Type { get; set; }
        public string Format_Expense_Code { get; set; }
        public string Format_Text_Code { get; set; }
        public string Format_Form_Type { get; set; }
    }
}
