//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRAINTEC_Inventory_Event_Buffer
    {
        public byte[] timestamp { get; set; }
        public int Entry_No_ { get; set; }
        public byte[] Source_Line_ID { get; set; }
        public string Item_No_ { get; set; }
        public string Variant_Code { get; set; }
        public string Location_Code { get; set; }
        public System.DateTime Availability_Date { get; set; }
        public int Type { get; set; }
        public decimal Remaining_Quantity__Base_ { get; set; }
        public byte Positive { get; set; }
        public int Transfer_Direction { get; set; }
        public decimal Reserved_Quantity__Base_ { get; set; }
        public int Action_Message { get; set; }
        public int Attached_to_Line_No_ { get; set; }
        public int Forecast_Type { get; set; }
        public byte Derived_from_Blanket_Order { get; set; }
        public string Ref__Order_No_ { get; set; }
        public decimal Orig__Quantity__Base_ { get; set; }
        public int Ref__Order_Type { get; set; }
        public int Ref__Order_Line_No_ { get; set; }
    }
}
