//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRAINTEC_G_L_Account_Where_Used
    {
        public byte[] timestamp { get; set; }
        public int Entry_No_ { get; set; }
        public int Table_ID { get; set; }
        public string Table_Name { get; set; }
        public string Field_Name { get; set; }
        public string Line { get; set; }
        public string G_L_Account_No_ { get; set; }
        public string G_L_Account_Name { get; set; }
        public string Key_1 { get; set; }
        public string Key_2 { get; set; }
        public string Key_3 { get; set; }
        public string Key_4 { get; set; }
    }
}
