//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_tbl
    {
        public int EmployeeNumber { get; set; }
        public string Name { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string SuplierAndIntrancit { get; set; }
        public string ChemicalAndMechaniacl { get; set; }
        public string FlintecStockManegement { get; set; }
        public string CenteringProcess { get; set; }
        public string MaterialRequest { get; set; }
        public string SerialNumberGenaration { get; set; }
        public string MachineshopBinHandling { get; set; }
        public string HTProcessControling { get; set; }
        public string QulityApprovels { get; set; }
        public string OutsourceHandling { get; set; }
        public string BinTrackingAndTransfering { get; set; }
        public string EMail { get; set; }
        public string Location { get; set; }
        public string Gaging { get; set; }
        public string Span { get; set; }
        public string Engineering { get; set; }
        public string AssemblyLine { get; set; }
        public string Phone { get; set; }
        public string Position { get; set; }
        public string Role { get; set; }
        public string Department { get; set; }
    }
}
